### ISSUE TITLE
Create wireframes for metadata editing interface

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#1]
UCSB metadata has complex subject metadata, with main subject terms related to geographic terms, as well as simple subject metadata (some of which are also geographic terms). The terms are governed by controlled vocabularies. For example, one object contains these two subjects:
```
<mods:subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
			<mods:topic valueURI="http://id.loc.gov/authorities/subjects/sh85062487">Hotels</mods:topic>
			<mods:geographic valueURI="http://id.loc.gov/authorities/names/n79041717">California</mods:geographic>
		</mods:subject>
<mods:subject authority="lcsh" authorityURI="http://id.loc.gov/authorities/subjects">
			<mods:geographic valueURI="http://id.loc.gov/authorities/names/n79081574">Santa Barbara (Calif.)</mods:geographic>
		</mods:subject>
```
Although the GUI for editing metadata will not include all metadata fields, it is likely to include Subject.  Wireframe at least two options for a user interface for editing metadata:
- [ ] editing subject metadata stored in a flat schema
- [ ] editing subject metadata stored in a complex schema

**Comment by mark-dce** [comment]
Create separate tickets for 
List of editable fields
List of displable fields
New person - local vs. lcnaf 
New subjects
Role assignment
Dates
