### ISSUE TITLE
Add link to object in fedora in show view

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#104]
- [ ] Administrators (only) should see a link to the underlying object in Fedora on the single item show view.  The link can be in or under the tools box.
- [ ] Regular users and unauthenticated users should not see the link

**Comment by jcoyne** [comment]
This is probably functionally equivalent to #76. Wait to see if more is necessary here.

**Comment by mark-dce** [comment]
Use case requirements are satisfied by #76, closing this ticket.
