### ISSUE TITLE
Import Date Other

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#105]
Path in MODS file:
mods:originInfo/dateOther

Predicate:
RDF::dcterms.date

Ruby name:
date_other

data type:
string (rdfs#Literal)  

This field will normally exist where a year or calendar date is not known and will contain something like "unknown" or "early 20th century".  Such items will not appear in date searches / facets.

**Comment by jcoyne** [comment]
We already have a `date` property stored in DC.date

**Comment by jcoyne** [comment]
Ah, looks like we're not using that property for anything else.
