### ISSUE TITLE
Fields to display on Image show page

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#109]
This is a continuation of story #103.  Here are the remaining fields that should be displayed on the Image show page:

* [ ] role / name pairs (list 'creator' first)
* [x] ark 
* [x] extent
* [x] place_of_publication
* [ ] rights_holder
* [ ] copyright_status
* [x] license
* [x] use_restrictions
* [x] institution
* [ ] Date(s)

**Comment by mark-dce** [comment]
Need metadata import and mapping for these stories to be committed first.

**Comment by mark-dce** [comment]
Blocked by #27, #114, #115, #116, #118, #133, #134,

**Comment by mark-dce** [comment]
Depenencies
#118  role / name pairs (list 'creator' first) 
#27 place_of_publication
#134 rights_holder
#114 copyright_status
#115 license
#116 use_restrictions
#133 institution

**Comment by mark-dce** [comment]
Closing as-is will open new tickets as necessary for individual fields on show and index views.
