### ISSUE TITLE
Import files from MODS

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#11]
ACCEPTANCE:
- [x] sample import of 4-6 MODS fields
We will show that at the demo and open the discussion about whether any fields can be left out, and which ones will display & be searchable.

**Comment by jcoyne** [comment]
We've got some of the fields importing, but not everything. Should we close this now and open new tickets for the rest?

**Comment by acozine** [comment]
I think this is good for now - since we did not have metadata requirements at the beginning, we will take an agile approach and get feedback on the subset before we implement the full enchilada. I updated the top comment on the ticket to reflect this.
