### ISSUE TITLE
Support Contributor as complex name types

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#117]
UCSB would like Contributor implemented as a [MODS name and role type](http://www.loc.gov/standards/mods/modsrdf-primer.html#name) rather than as a simple roleProperty predicate.  The MODS example relies on blank nodes.

Complex value

    Name: Name
    Type: unconstrained string (authority = local) | lcnaf (authority = naf)
    Multi-valued?: No

    Name: Name Type
    Type: madsrdf:Name [ madsrdf:CorporateName , madsrdf:FamilyName , madsrdf:PersonalName , madsrdf:ConferenceName ]
    Multi-valued?: No

    Name: Role
    Type: MARK Relator - http://www.loc.gov/loc.terms/relators/dc-relators.xml
    Multi-valued?: No

    Name: Authority
    Type: ["naf", "local"] naf = 
    Multi-valued?: No

**EXAMPLE**
For the MODS input
```xml
<mods:name type="corporate" authority="naf" authorityURI="http://id.loc.gov/authorities/names" 
	valueURI="http://id.loc.gov/authorities/names/n87914041">
		<mods:namePart>American Film Manufacturing Company</mods:namePart>
		<mods:role>
			<mods:roleTerm type="text" authority="marcrelator"
				authorityURI="http://id.loc.gov/vocabulary/relators"
				valueURI="http://id.loc.gov/vocabulary/relators/pbl">Publisher</mods:roleTerm>
		</mods:role>
</mods:name>
```

create a graph something like
```text
adrl12356		dcterms:contributor		#BlankNodeX
#BlankNodeX		rdfs:label				"American Film Manufacturing Company"
#BlankNodeX		rdfs:type				madsrdf:CorporateName
#BlankNodeX		roleRelationshipRole	http://id.loc.gov/vocabulary/relators/pbl
#BlankNodeX		roleRelationshipName	http://id.loc.gov/authorities/names/n87914041
```

------------------
For the MODS input
```xml
	<mods:name usage="primary" type="personal" authority="local">
		<mods:namePart>Conway, Joel</mods:namePart>
		<mods:role>
			<mods:roleTerm type="text" authority="marcrelator"
				authorityURI="http://id.loc.gov/vocabulary/relators"
				valueURI="http://id.loc.gov/vocabulary/relators/col">Collector</mods:roleTerm>
		</mods:role>
	</mods:name>
```

create a graph something like
```text
adrl098765		dcterms:contributor		#BlankNodeY
#BlankNodeY		rdfs:label				"Conway, Joel"
#BlankNodeY		rdfs:type				madsrdf:PersonalName
#BlankNodeY		roleRelationshipRole	http://id.loc.gov/vocabulary/relators/col
```

**Comment by jcoyne** [comment]
This seems contraindicated by the MODS RDF Primer:
> When the role is a vocabulary term it is treated as described in Property  a Vocabulary Term.  as in the following triple:
                        {MODS resource}  {roleProperty} madsrdf:Name

**Comment by jcoyne** [comment]
>UCSB would like Contributor implemented as a MODS name and role type rather than as a simple roleProperty predicate

Your words or theirs?

**Comment by mark-dce** [comment]
From Chrissy via https://docs.google.com/a/curationexperts.com/spreadsheets/d/1YnWQOKsbwfbToGYt018Q3CRXLycysUJ2S6o3j8SpvzI/edit#gid=513417340

"Complex:
- Name: Name
- Type: Text string
- Multi-valued?: No

- Name: Name Type
- Type: Controlled vocabulary
- Multi-valued?: No

- Name: Role
- Type: Controlled vocabulary
- Multi-valued?: No

- Name: Authority
- Type: Controlled vocabulary
- Multi-valued?: No

- Name: Authority ID
- Type: Text string
- Multi-valued?: No"

**Comment by jcoyne** [comment]
@mark-dce So, she's saying "this is how it works now." I don't think Chrissy has a good understanding of RDF, so she's framing the requirements in terms of current implementation.  As you indicated before, she doesn't care if we store it in RDF, so if we go down that path, we should do things in an RDF way.   If it needs to work like the existing system works, we should just write a MODS editor.

**Comment by mark-dce** [comment]
Going with the version covered in #118, #123, #125
