### ISSUE TITLE
Import Additional Role Types

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#118]
Ensure that UCSB can support the roles they have identified in their image data:
>Architect, Artist, Collector, Contributor, Creator, Landscape architect, Performer, Photographer, Vocalist, Composer    

Make sure that other anticipated roles are supported or easy to add.

- [x] Map the following roles when they appear in mods:name/role/roleTerm with a mods:name - use the full list here: http://lcweb2.loc.gov/diglib/loc.terms/relators/dc-contributor.html

- [x] If any other role appears, map the name to DC.contributor and log an error "the specified role for for name _nameInImportFile_ in not a valid marcrelator role"

- [x] If no role appears in the name node, map the name to DC.contributor and log an error "no role was specified for name _nameInImportFile_"

**Comment by mark-dce** [comment]
Explain to Chrissy that this looses name type (corporate, personal, family, conference), primary indication, and currently discards LCNAF URIs.  Compare with cost and benefit of #117

**Comment by jcoyne** [comment]
This approach does not have to loose the name type. That is a separate concern. One can do:
```xml
<name xmlns="http://www.loc.gov/mods/rdf/v1#">
    <PersonalName xmlns="http://www.loc.gov/mads/rdf/v1#" rdf:about="idname103263352">
        <label xmlns="http://www.w3.org/2000/01/rdf-schema#">Epstein, Daniel Mark.  </label>
        <elementList rdf:parseType="Collection">
             <FullNameElement>
             <elementValue>Epstein, Daniel Mark.</elementValue>
             </FullNameElement>
         </elementList>
   </PersonalName>
</name>
<!-
-**** Roles for this name.
-->
<relator:spk rdf:resource="idname103263352"/>
```

```

**Comment by jcoyne** [comment]
Since we're linking to entities such as http://id.loc.gov/authorities/names/n87914041 we can look at the linked record and see that it is a CorporateName.

**Comment by mark-dce** [comment]
There's a full list of MARC relator labels and URIs on the wiki at https://github.com/curationexperts/alexandria-v2/wiki/MARC-Relator-Label-to-URI-mappings

**Comment by mark-dce** [comment]
@jcoyne Chrissy has indicated that 'Vocalist' (or 'vocalist') is one of the current roles - if it's going to cause an problem because Vocalist is deprecated, can you contact Chrissy and figure out a resolution?

**Comment by jcoyne** [comment]
@mark-dce Chrissy indicated that she would update all the metadata so that Vocalist is coded as Singer.
