### ISSUE TITLE
Import Collections from MODS

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#12]
Each collection should have a Title, an Identifier, and a (node) ID. An example of their metadata:
```
<mods:relatedItem type="host">
			<mods:titleInfo>
				<mods:title>Santa Barbara picture postcards collection</mods:title>
			</mods:titleInfo>
			<mods:identifier type="local">SBHC Mss 36</mods:identifier>
		</mods:relatedItem>
```
The mods:title should become the Title. The mods:identifier type="local" should become the Identifier with no modifications, and should be modified to remove all spaces and make all characters lower case to create the ID, which we will use in the RESTful URLs.

**Comment by val99erie** [comment]
The sample data file cusbspcsbhc78_100239.xml has 2 entries for "relatedItem".

For this sample, the Image should belong to a Collection with:
id:  "sbhcmss78"
title: "Joel Conway / Flying A Studio photograph collection"

Question:  Should we do anything with the 2nd entry, "Series 4: Glass Negatives"?  If so, what metadata field should it map to?

```
<mods:relatedItem type="host">
  <mods:titleInfo>
    <mods:title>Joel Conway / Flying A Studio photograph collection </mods:title>
  </mods:titleInfo>
  <mods:identifier type="local">SBHC Mss 78</mods:identifier>
</mods:relatedItem>

<mods:relatedItem type="series">
  <mods:titleInfo>
    <mods:title>Series 4: Glass Negatives</mods:title>
  </mods:titleInfo>
</mods:relatedItem>
```

**Comment by val99erie** [comment]
Regarding my above question about the "series" entry in the MODS file:  I'll open a new story about that.
