### ISSUE TITLE
Import Institution

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#133]
Path in MODS file:
mods:location/physicalLocation

Predicate:
OREGONDIGITAL.contributingInstitution

Ruby name:
institution

data type:
URI - typically LOC Cultural Heritage Organizations: http://id.loc.gov/vocabulary/organizations

**Comment by mark-dce** [comment]
From Chrissy on 2/26

>Please use URI. I am still working on which URI should be used (our LC Name authority or our Cultural Heritage Organization authority). I will update here once I get that worked out.

**Comment by mark-dce** [comment]
From Chrissy on 3/4

>For the institution name, please use the LC Cultural Heritage URI for the UCSB Library: http://id.loc.gov/vocabulary/organizations/cusb.html

Fixtures have been updated and a pull request has been submitted for the stash demo data, so I've unblocked this ticket.

**Comment by val99erie** [comment]
From mods file:
mods:location/physicalLocation[@valueURI]

**Comment by jcoyne** [comment]
It doesn't look like `mods_demo_set/demo_sbhcmss36_SantaBarbaraPicturePostcards/*` have been updated to have `@valueURI`. You might want to shoot Chrissy an email.

**Comment by tonyc** [comment]
We were talking about this yesterday... I believe the current plan according to @mark-dce is to make the changes in our fork of the mods_demo_set repo, and then do an audit at a later date.

**Comment by mark-dce** [comment]
@tonyc @jcoyne - Yes, lets just update our copy of the mods_demo_set and synchronize with UCSB at the end.  I e-mailed Chrissy and she confirmed this would work for her yesterday.

**Comment by tonyc** [comment]
Great - I'm going to need to do this shortly for this ticket, so I can get these changes made. There are a lot of them but a projectwide search-and-replace should handle it easily.

**Comment by tonyc** [comment]
Work finished & merged - demo data for physicalLocation will be handled in #157
