### ISSUE TITLE
Import Rights Holder

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#134]
Path in MODS file:
mods:extension/copyrightHolder

Predicate:
RDF::URI('http://opaquenamespace.org/rights/rightsHolder')

Ruby name:
rights_holder

Vocabulary:
URI from LCNAF or Local Name authority file - similar to how creator/contributor/role names are handled.  find_or_create a new Local Name if a URI is not provided

**Comment by mark-dce** [comment]
Sample fixtures added to repo: 

**cusbmss228-p00001.xml, cusbmss228-p00003.xml**
<mods:extension>
	...
	<copyrightHolder>http://id.loc.gov/authorities/names/n85088322</copyrightHolder>
</mods:extension>

**

**Comment by val99erie** [comment]
I sent an email to Chrissy asking if we can change the XML to look like this instead:
<copyrightHolder valueURI="http://id.loc.gov/authorities/names/n85088322">Regents of the University of California</copyrightHolder>

**Comment by mark-dce** [comment]
@val99erie Do you mean change the XML node text to be the string?  I'm pretty sure Chrissy wants us to store the URI rather than the string - it looks like she updated the sample data in a recent commit https://stash.library.ucsb.edu/projects/CMS/repos/mods-for-adrl/commits/8930ab32f57a3fe0e2d275ea750ad0325d18ed31 so that it looks like:

<copyrightHolder valueURI="http://id.loc.gov/authorities/names/n85088322">University of California (System). Regents</copyrightHolder>

**Comment by mark-dce** [comment]
@val99erie sorry - I just realized that's what you said, but you needed to put the text in backticks...

**Comment by jcoyne** [comment]
I edited @val99erie's comment so that it formats correctly

**Comment by tonyc** [comment]
closed by https://github.com/curationexperts/alexandria-v2/pull/152
