### ISSUE TITLE
Handle copyrightHolder as a local name if no URI provided

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#135]
Treat copyrightHolder names similarly to authors/creators:
- if a URI is provided, store the URI as the object of the predicate
- if a string is provided, look it up in the local name authority file, use the local name URI if there's a match
- if there's no URI and no matching name, create a new name and use the URI for the new entry

**EXAMPLE**

```xml
<mods:extension>
	<copyrightHolder>Ajao, John</copyrightHolder>
</mods:extension>
```

For a record like this, the system should look in the local name authority for a match and create a new entry if none is found.

**Comment by jcoyne** [comment]
Looks like this is already done
