### ISSUE TITLE
Vocalist should be transcoded to Singer

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#137]
Because Vocalist (http://id.loc.gov/vocabulary/relators/voc.html) is deprecated.

**Comment by jcoyne** [comment]
I don't think we need to do this because Chrissy said she'd do it on their side.

**Comment by jcoyne** [comment]
Added question just so we can confirm with Chrissy.

**Comment by mark-dce** [comment]
Confirm at Sprint demo and then close this ticket

**Comment by mark-dce** [comment]
Covered at sprint demo.  No further coding required.
