### ISSUE TITLE
Collection index page

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#15]
When you visit the catalog page with no search results, you currently get the default Blacklight welcome message from `app/views/catalog/_home_text.html.erb`.  We need to replace it with something.

Here's what v1 looks like:
http://alexandria.ucsb.edu/catalog

**Comment by val99erie** [comment]
Should we have the same 'Browse by Collection' list?  Should we include ETDs, even though we aren't yet importing ETDs?  Or should we replace the ETDs link with a link to Images?

**Comment by acozine** [comment]
As a first step, we are expanding, not replacing, the existing Alexandria site. We are not including ETDs in the new codebase yet. The current system for ETDs is working and in active use, and it's on Fedora 3.x. Ultimately, though, the two systems will get integrated, so yes, let's include 'Browse by Collection' on the catalog page.

**Comment by val99erie** [comment]
It looks like there is a mock-up of what they want, so we can use this as a guide:
https://drive.google.com/a/gentiansoftware.com/#folders/0BytolfRBVL3rZlkzNnotVDFKS1U

**Comment by jcoyne** [comment]
![screen shot 2015-02-02 at 10 00 22 am](https://cloud.githubusercontent.com/assets/92044/6003601/887f1602-aac2-11e4-8feb-d27a1f1287e9.png)

**Comment by mark-dce** [comment]
This should be the landing page if you click on the "Browse by Collection" on the application home page (see http://sandbox.curationexperts.com - middle of page)
