### ISSUE TITLE
Date faceting and sorting

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#153]
Use the following rules to determine which date to use for sorting and faceting in cases where multiple dates exist for an object:
- use date_created if it has a valid start value
- else use date_issued if it has a valid start value
- else use date_copyrighted if it has a valid start value
- else use date_submitted if it has a valid start value
- else use date_accepted if it has a valid start value

If multiple dates exist of the same type use the earliest (min) start and latest (max) finish value from that date type

If only the start date exists, treat the date as a point date.

If a start and finish date exist, treat the date as a range for faceting purposes.

**Comment by mark-dce** [comment]
Blocked until #150 is complete

**Comment by jcoyne** [comment]
Unblocked

**Comment by val99erie** [comment]
We do not currently have date_accepted or date_submitted, so I did not include those.  I selected the dates in the following order:
```[:created, :issued, :date_copyrighted, :date_other, :date_valid]```
