### ISSUE TITLE
Handle complex dates in metadata editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#154]
Provide a way to input and modify complex dates (date format described in #150).

An item may have one or more dates associate with it.  Each date is represented by a date type predicate pointing to an edm:timespan graph which provides narrative, year, or calendar-date information for start and optionally end dates.

In the sample below, a variety of possible date expressions are shown which do not represent a single consistent object.  An actual object will frequently only have a single date associated with it.

![adrl2 - 149 - date input](https://cloud.githubusercontent.com/assets/3064318/6680886/91e30a84-cc2b-11e4-9ded-34d3f1e4e911.png)

**Comment by mark-dce** [comment]
Blocked until #150 is complete

**Comment by jcoyne** [comment]
Unblocked

**Comment by tonyc** [comment]
WIP screenshot:


![image](https://cloud.githubusercontent.com/assets/10182/6984299/01919f48-d9ed-11e4-83bc-867f1a5445fe.png)

**Comment by tonyc** [comment]
WIP screenshot

![date-editor-wip](https://cloud.githubusercontent.com/assets/10182/6984312/19f78700-d9ed-11e4-8b9d-1ff977e72f22.png)
