### ISSUE TITLE
Handle role and name lookup and assignment in editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#156]
**STORY**
Each record in ADRL may be associated with one or more names (agents) who hold one or more roles in relation to the object.

The role relationships are defined by MARC relator terms (see #118 and [MARC relator module](https://github.com/curationexperts/alexandria-v2/blob/763f086c660e378a84cf6bcf299c51062bdb88b1/app/models/concerns/relators.rb) ).  Names come either from the Library of Congress Name Authority File http://id.loc.gov/authorities/names.html or a local authority for names that do not yet exist in the LCNAF vocabulary - i.e. local Santa Barabara and California people names that might not be recognized by LoC yet.  The editor should auto-suggest names.  If a name is typed that doesn't exist in either LCNAF or the local name authority, the user should have some means to create a new entry in the local authority.

**ACCEPTANCE**
- [ ] The editor should provide a role selection limited to the known MARC relator roles
- [ ] The list of roles should begin with 'creator' and 'contributor' followed by the full list of available roles in alphabetical order
- [ ] contributor and creator may be repeated in the role list in their correct alphabetical position, or they may appear only at the top of the list
- [ ] The editor should provide autosuggest options as the user types in a name
- [ ] Typing a new name over a pre-filled entry should provide new auto-suggest and replace the existing entry    
- [ ] The input form should let the user select which vocabulary they want to search against (LCNAF or Local Name authorities)
- [ ] The autosuggest should accept both primary and variant names (e.g. Adams, Ansel, 1902-1984 or Adams, Ansel Easton, 1902-1984 for http://id.loc.gov/authorities/names/n79056359)    
- [ ] The editor should store the name as it's URI
- [ ] The editor should allow multiple name/role pairs per object
- [ ] Entries without a name entered should not be saved
- [ ] On load, the form should display all existing role/name pairs and provide a blank entry section at bottom   
- [ ] If the user enters a name that doesn't have a match in the name authority, he will see some kind of feedback that the name won't be saved.  (Or:  Somehow prevent the user from inputting non-matching text)
- [ ] The fields from the wireframe should replace the existing 'creator' and 'contributor' fields in the metadata editor (i.e. there should not be dedicated creator and contributor fields)

**WIREFRAME**
![adrl2 - 156 - contributor input v2](https://cloud.githubusercontent.com/assets/3064318/6901254/bd5ad8bc-d6d1-11e4-9388-a27ed8e5ae9a.png)

**Comment by val99erie** [comment]
Assumption:  Local Names already exist.  We aren't going to create them on-the-fly in this form.  If you want a new local name, you have to create it ahead of time, and then you can add it onto this form.
