### ISSUE TITLE
Get sample MARC records for 5 ETD objects

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#160]
Get 5-10 sample MARC records from UCSB corresponding to existing ETDs.

**Comment by acozine** [comment]
From Chrissy:
Below you will find links to several sample ETDs and their associated MARC records in the test version of our ILS. We are right in the middle of updating these records, and they are not yet available in the production version of our catalog. These records are pretty close to being finalized, but please be aware that we still have at two future modifications planned (possibly some minor tweaks as well): 1) the addition of the ADRL permalink (which will include the ARK) and 2) the addition of author supplied keywords. If you would prefer either the MARC or MARCXML version of these files, please let me know and I can work with Ana to get you copies of them next week.

Sacred Travels: Religious Identity and its Effect on the Reception of Travelers in the Eastern Roman Mediterranean / Bloom, Ibukun J. 
ADRL 1.0: http://alexandria.ucsb.edu/lib/ark:/48907/f3pn93hx
Test ILS Server: pegasus-test.library.ucsb.edu/F/?func=direct&doc_number=003751821&local_base=SBA01PUB

Writing Revelation: Mary Baker Eddy and Her Early Editions of "Science and Health", 1875--1891 / Voorhees, Amy Black. 
ADRL 1.0: http://alexandria.ucsb.edu/lib/ark:/48907/f3gq6vqd
Test ILS Server: pegasus-test.library.ucsb.edu/F/?func=direct&doc_number=003978845&local_base=SBA01PUB

The "Strong Black Women Collective": Intergroup delineations among Black and White female friendship social support networks / Davis, Sharde’ Marie. (Note: ADRL includes supplementary files)
ADRL 1.0: http://alexandria.ucsb.edu/lib/ark:/48907/f3wm1bb2
Test ILS Server: pegasus-test.library.ucsb.edu/F/?func=direct&doc_number=003891522&local_base=SBA01PUB

These Are a Few of My Favorite Things: The Cultural Meaning of the Tree / Dryden, Patrick Neil.  (Note: ADRL includes supplementary files)
ADRL 1.0: http://alexandria.ucsb.edu/lib/ark:/48907/f3000017 
Test ILS Server: pegasus-test.library.ucsb.edu/F/?func=direct&doc_number=003751846&local_base=SBA01PUB

**Comment by jcoyne** [comment]
@acozine please ask Crissy for the MARC version of the files

**Comment by mark-dce** [comment]
E-mailed a response to Chrissy's original e-mail requesting downloadable MARC records.

**Comment by acozine** [comment]
I requested MARC files this morning, and intentionally left the ticket open. My response didn’t come through on the list, though - I probably needed to hit reply-all instead of reply.

Alicia

**Comment by mark-dce** [comment]
sample data is in /opt/download_root

see here for proquest <-> marc <-> ark mappings: https://docs.google.com/a/curationexperts.com/spreadsheets/d/1KxqmCjz5PLRD3Iz4s0lAKcREqriEKfrD9gxFaxNd-TA/edit?usp=sharing
