### ISSUE TITLE
Authentication (LDAP or off-campus proxy)

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#17]
Use the devise_ldap_authenticatable gem to allow LDAP logins?

**Comment by val99erie** [comment]
For reference, here's how it currently works in Alexandria v1.
There are 3 types of logins:

1.  On-campus:  All users with certain IP address ranges are able to see non-embargo items without having to authenticate.

2. Off-campus proxy login:
http://alexandria.ucsb.edu/welcome/off_campus_login

3. Admin users login (using devise?) for importing ETDs.

**Comment by val99erie** [comment]
If we remove the off-campus proxy login, then there is associated code that should be removed too.

* [ ] Remove dead code for off-campus login

**Comment by mark-dce** [comment]
Yes, please remove any dead code for off-campus proxy.  We'll address the larger Devise LDAP auth issue later; for now we'll use Devise database auth

**Comment by val99erie** [comment]
For the first release (admin functionality only), we'll be using devise login with users and roles stored in the database.

For the later release (discovery functionality, non-admin users), we'll hook up to UCSB's LDAP.

At some point in the future, John mentioned that they might switch to a UC-wide Shibboleth instead of UCSB-only LDAP.

For v2, we won't be using the off-campus proxy login at all.

For now, we have all the code we need.  The devise database login has already been implemented, so the only thing we have left to do is remove dead code.
