### ISSUE TITLE
Permit local names to be Deleted

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#172]
- [x] There is a link to delete a local name (agent) authority entry (The link can be in the show tools or on the local_authorities index page, or someplace that makes sense)
- [x] If the name is in use, the system should indicate that and cancel the delete operation.*
- [x] The name should no longer appear in any auto suggest fields on the editor.

*NOTE: If a local name is still in use, it must be manually removed for each record or removed by merging it with another local name #178.

**Comment by val99erie** [comment]
What about the case where some live objects point to the local name object?  Is it allowed to be deleted even if something has a reference to it?  Should those references be deleted?

**Comment by mark-dce** [comment]
What I really mean is 'the record is marked as being no longer available for assignment to new objects'

That's why I said tombstone rather than outright delete, but maybe that still implies a specific technical implementation that I didn't mean.  I.E. the record for the name should stay around and existing objects that point to the URI could still use it to resolve the label, but the name shouldn't appear in the auto suggest list on new objects once it's been tombstoned.  Maybe 'tombstone' is the wrong word to use if fedora won't return the record if it's tombstoned.

**Comment by jcoyne** [comment]
This seems ill conceived. How about ensuring nothing points at the record and then just deleting the resource?  We could say "can't be deleted because it's referenced by x, y and z ..." then the have to clean up the data before removing it.

**Comment by mark-dce** [comment]
@jcoyne there's three cases
1. There's a local name that nothing points to
2. There's a local name in use that I don't want others to use in the future for new assignments, but I'm too lazy to clean up the existing uses
3. There's a local name in use that I want to replace with another name - this is the merge story #178 

I was making the assumption that we could merge cases 1 & 2 in a way that causes the application not to allow the name to be assigned when creating new objects (i.e. it doesn't appear in the selection list of available options)

**Comment by mark-dce** [comment]
To Justin's point, we could disallow case number 2 and just force the user to either delete the specific predicates or merge names.  I'd be ok with that - I just thought creating a clean user experience for "can't be deleted because it's referenced by x, y and z ..." could be ugly if someone did a batch ingest of 500 items that had a bad name in them.

**Comment by mark-dce** [comment]
Revise acceptance to only allow deletion of unused names; otherwise, the references need to be manually removed or merged.
