### ISSUE TITLE
Add description_standard to Metadata Editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#173]
- [ ] [description_standard](https://github.com/curationexperts/alexandria-v2/blob/55926fc34fad430e39a56dfb17d007c9740727ae/app/models/concerns/metadata.rb#L125) should be editable in the metadata editor
- [ ] It should point to a string literal
- [ ] Values should be constrained to the set ['aacr', 'rda', 'dacs', 'dcrmg', 'local', 'none']
- [ ] Values should be stored in a YAML config file

**Comment by chrissyrissmeyer** [comment]
Please add the values 'fgdc' and 'iso19115' to the list.
