### ISSUE TITLE
Add language_of_cataloging = english predicate/object to all repo items

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#174]
- [ ] all items should include a static assertion that their language of cataloging is english (http://id.loc.gov/vocabulary/iso639-2/eng)  when exported to turtle or other formats

We need to find a predicate or discuss with Chrissy that this will not be included in data exports.

**Comment by val99erie** [comment]
Question:  We need to decide the predicate

**Comment by jcoyne** [comment]
This doesn't make any sense in a RDF graph. The language should be asserted on the strings themselves.

**Comment by mark-dce** [comment]
Ok, that's fair.  I'm not seeing language assertions on any of our turtle exports though.  How do we assert the language of a specific statement/value.

**Comment by ilessing** [comment]
We can close with a "won't fix"    Chrissy Said!
