### ISSUE TITLE
Attach access metadata to images on ingest

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#18]
What should the access be for images imported on the command line?

**Comment by acozine** [comment]
For now, all images imported on the command line should be open access. Everything we are working with up to now is publicly available already. As a next step, make this configurable - either at the command line for the whole batch, or with an extra field in the import listing the desired access level.

**Comment by val99erie** [comment]
For now assume we can hard-code access levels to:
* Admin group is discover/read/edit
* Staff group is discover/read/edit
* Public group is discover/read (no edit)

Need to confirm assumptions with UCSB

**Comment by jcoyne** [comment]
Are we just making up "staff" and "admin" groups for now?

**Comment by jcoyne** [comment]
We will not set "admin" since they are a strict subset of "staff"

**Comment by jcoyne** [comment]
Waiting to decide if we are going to do APOs
