### ISSUE TITLE
Add form_of_work to the editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#183]
- [ ] Genre (form_of_work) should be displayed and editable
- [ ] There should be a drop down that lets the user select the desired vocabulary - [aat, local subjects, lc-tgm]

NOTE: MARC Genre Terms (marcgt) will be added at a later date once an online endpoint has been created for that vocabulary.

![adrl2 - 183 - genre](https://cloud.githubusercontent.com/assets/3064318/6989144/c7ed1dfe-da1d-11e4-9a32-19b19b8a80f7.png)

**Comment by jcoyne** [comment]
Why would one add a "subject" to a "genre"?

**Comment by mark-dce** [comment]
Because otherwise we have to make a separate local genre vocabulary - this way if there's anything really missing from one of public vocabs - like maybe I'm storing a research data set (i.e. genre = data set) I can create a URI for it if that doesn't happen to be in AAT or LC TGM.

**Comment by mark-dce** [comment]
I'm happy if you want to set up a separate local genre vocab, but it seems like overkill.

**Comment by mark-dce** [comment]
Upon further reflection - we should be able to do without a local genre vocabulary for the initial release.  So for now, just AAT and LCTGM
