### ISSUE TITLE
Ensure contributing institution is being imported

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#184]
I can't find contributing institution on any of the objects on Sandbox.  It looks like the code and sample data should have been updated in stories #133 and #157.

- [ ] ~~Ensure that updated code has been deployed and institution is being imported~~
- [x] I can see the institution name on the show page
- [x] I can see the institution URI in the turtle output
- [x]  we've noted 1 or two sample objects to show for the demo

**Comment by val99erie** [comment]
Sample objects for demo:
* cusbmss228-p00001
* cusbmss228-p00003
* cusbspcmss36_110108
* cusbspcsbhc78_100239
* sbhcmss78_FlyingAStudios_collection
