### ISSUE TITLE
Use DC.rightsHolder for rights_holder

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#191]
Discuss with Justin & Chrissy whether to change implementation.

**Comment by jcoyne** [comment]
Everything seems better than opaquenamespace.org

**Comment by jcoyne** [comment]
Ah, I think I see the reason. The Domain of hasRightsRelatedAgent is a RightsStatement, so we'd have to add RightsStatement to support that.

**Comment by mark-dce** [comment]
I got e-mail confirmation back from Chrissy - we should use DC.rightsHolder for the rights_holder predicate.
