### ISSUE TITLE
Add copyright_status to editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#192]
- [x] [copyright_status](https://github.com/curationexperts/alexandria-v2/blob/master/app/models/concerns/metadata.rb#L83) is displayed and editable 
- [x] choices are constrained to [copyrighted, public domain, unknown] - see URIs below

Vocabulary:

Label | URI
--------|----------
copyrighted	| http://id.loc.gov/vocabulary/preservation/copyrightStatus/cpr
public domain	| http://id.loc.gov/vocabulary/preservation/copyrightStatus/pub
unknown		| http://id.loc.gov/vocabulary/preservation/copyrightStatus/unk

**Comment by chrissyrissmeyer** [comment]
No changes to the values on this list.
