### ISSUE TITLE
Add license to editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#193]
- [ ] [license](https://github.com/curationexperts/alexandria-v2/blob/master/app/models/concerns/metadata.rb#L85) is displayed and editable in the editor 
- [ ] License is constrained to the values below
- [ ] The constraint list is stored as a YAML config file

Label 		| URI
-------------------	|----------
Public Domain	| http://creativecommons.org/publicdomain/mark/1.0/
CC0  |  http://creativecommons.org/publicdomain/zero/1.0/
CC-BY  |  http://creativecommons.org/licenses/by/4.0/
CC-BY-SA  |  http://creativecommons.org/licenses/by-sa/4.0/
CC-BY-ND  |  http://creativecommons.org/licenses/by-nd/4.0/
CC-BY-NC  |  http://creativecommons.org/licenses/by-nc/4.0/
CC-BY-NC-SA  |  http://creativecommons.org/licenses/by-nc-sa/4.0/
CC-BY-NC-ND  |  http://creativecommons.org/licenses/by-nc-nd/4.0/
Education Use Only  |  http://opaquenamespace.org/ns/rights/educational/
Free Access - No Re-Use  |  http://www.europeana.eu/rights/rr-f/
Rights Reserved - Restricted Access  |  http://www.europeana.eu/rights/rr-r/
Orphan Works  |  http://opaquenamespace.org/ns/rights/orphan-work-us/
Unknown  |  http://www.europeana.eu/rights/unknown/

**Comment by chrissyrissmeyer** [comment]
No changes to the values on this list.
