### ISSUE TITLE
Add Getty Thesaurus of Geographic Names to list of available vocabularies for Subjects

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#197]
- [ ] Add the Getty TGN to the available vocabularies in Alexandria: https://github.com/curationexperts/alexandria-v2/blob/master/config/initializers/controlled_vocabularies.rb
- [ ] Add the Getty TGN to the list of available subject vocabularies in the metadata editor (see wireframe in #158

**Comment by jcoyne** [comment]
Added to questioning_authority in https://github.com/projecthydra-labs/questioning_authority/pull/83

**Comment by mark-dce** [comment]
The simple solution assumes we implement a flat search and user interface.  If UCSB desires a hierarchical search or to browse hierarchy, the solution becomes significantly more complex and we would need to develop wireframes to show exactly how hierarchical browse or search should work.

**Comment by mark-dce** [comment]
There's no longer a current requirement for TGN.  We've decided to close this ticket and will open a new ticket when there is a specific requirement for a collection that uses TGN, Open Geo Names, or some other missing vocab.
