### ISSUE TITLE
Add Local Subject authority to list of vocabs in metadata editor

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#199]
- [ ] Add the Local subject authority to the list of available subject vocabularies in the metadata editor (see wireframe in #158)

**Comment by val99erie** [comment]
I think this is already done, unless I'm misunderstanding something.  When I create a new record, under the "Subject" drop-down, I see "Local Subjects" and "Local Names" as choices.

**Comment by jcoyne** [comment]
I agree. Closing.
