### ISSUE TITLE
Create wireframes for Advanced Search interface

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#2]
As a user, I want to search and facet for materials without worrying about how the metadata is structured. For example, if I'm searching for information about historic hotels in Santa Barbara, I want to find relevant materials without knowing whether my search terms are simple subjects (Santa Barbara) or complex subjects (Hotels - California). 

Wireframe at least two options for the user interface for searching that reflect the storage options for subject metadata. Related to #1.

**Comment by mark-dce** [comment]
I think we meet the search acceptance criteria.  Closing and will open a new issue if more specific requirements arise.
