### ISSUE TITLE
Merge Local Subjects

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#203]
Provide a means to merge two local subject entries:
- [x] Select one of the subjects using the edit icon
- [x] Provide a "Merge Into" option (see local names wireframe below)
- [ ] Run a background job to update all reference from the original URI (being edited) to the URI selected in "Merge Into"
- [x] Delete the original URI

=======================
![adrl2 - 178 - merge local names](https://cloud.githubusercontent.com/assets/3064318/6911912/d9a4923c-d72c-11e4-9fc1-362590783cdf.png)

**Comment by jcoyne** [comment]
We already have the "Merge this Record" functionality.  Does this cover it, or should we spend time making it look like the wireframes?

**Comment by mark-dce** [comment]
The wireframe above had both "new" above the OR line and "merge" below the line.  Ours has all the functions shown in the merge portion:
<img width="526" alt="adrl2 - 203 - merge form" src="https://cloud.githubusercontent.com/assets/3064318/12177117/34453ffc-b530-11e5-99ca-4e6117a2a89d.png">

**Comment by mark-dce** [comment]
I can't merge records that are already in use.  Coming this ticket and opening a new bug ticket though, since the functionality seems to be there but not working properly.  See #480
