### ISSUE TITLE
Add constrained option list for "Digital origin" field

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#208]
- [ ] Set up a constrained list of options for the "digital origin" input in the editor
- [ ] Store the source list in a YAML config file
- [ ] Store the vales as string literals in the object graph (i.e. these won't have URIs)

**INITIAL LIST OF VALUES**
"digitized other analog"
"born digital"

NOTE: Chrissy will provide additional list of values in the comments or UCSB will edit the config file later.

**Comment by chrissyrissmeyer** [comment]
Please add the values "reformatted digital" and "digitized microfilm"
