### ISSUE TITLE
Add constrained list for the "Holding sub-location" field

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#209]
- [ ] Set up a constrained list of options for the "Holding sub-location" input in the editor
- [ ] Store the source list in a YAML config file
- [ ] Store the vales as string literals in the object graph (i.e. these won't have URIs)

**INITIAL LIST OF VALUES**
"Department of Special Collections"
"Main Library"

NOTE: Chrissy will provide additional list of values in the comments or UCSB will edit the config file later.

**Comment by chrissyrissmeyer** [comment]
Please add "Map & Imagery Laboratory" to the initial list of values.

**Comment by chrissyrissmeyer** [comment]
Sorry for adding a comment to a closed ticket, but would it be possible to change the "Department of Special Collections" to "Department of Special Research Collections"? Or, could you show someone on the UCSB team how to do this?

Special Collections recently underwent a name change, and the administration would like this reflected in ADRL. I will update all of the descriptive metadata records to reflect the new name as well.

**Comment by mark-dce** [comment]
@chrissyrissmeyer - I added a new ticket #261 to make this change.
