### ISSUE TITLE
Metadata editor should show when I'm in a controlled vocabulary field

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#225]
It's not clear when I'm typing in a plain old string or when I should wait for a pop-up list of suggestions.   

- [ ] Fields like "Subject (location)" should tell me to wait until the suggestion list appears - this could be as simple as putting the words "auto-complete" after the field label or as the default & disabled value in the field itself.  Other ways to flag this are ok too.

**Comment by jcoyne** [comment]
Current fix put spinners on all text fields, so reopening.

**Comment by jcoyne** [comment]
Fixed in 09fdaa0f9b65356a5d245254fac526f2c8976e5d
