### ISSUE TITLE
Secondary images do not display

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#234]
If I open a show page for an object with multiple images (for example, front and back of a postcard):
http://sandbox.curationexperts.com/lib/ark:/99999/fk49p37417#
the right and left arrows for navigating between images show up, and clicking one adds '#' to the end of the URL, but only the default image displays. The rails log shows no errors.

**Comment by jcoyne** [comment]
Javascript is breaking on "relators" is not defined.
