### ISSUE TITLE
ETD Fields to store in Index for show view

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#242]
At a minimum these fields:
Author
Published
Date Created
Format
Description
Notes
Dissertation
Bibliography
Summary
Statement of responsibility
Genre
Keywords
Thesis advisor
Committee member
Degree grantor
Discipline
Language
ISBN
ARK
Permalink
Copyright

**Comment by mark-dce** [comment]
@mark-dce to finalize show view wireframe as input to this story
