### ISSUE TITLE
ETDs should have access controls

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#244]
On the search results page.

**Comment by jcoyne** [comment]
This needs to be imported from the supplemental xml from proquest. Access could be open or embargoed

**Comment by mark-dce** [comment]
Needs @mark-dce to write detailed access control requirements and data from #268 to be available.

**Comment by acozine** [comment]
Valerie and I dug around for some details on this story. Here's what we discovered:
There are three different sets of rules for ETD access, because ProQuest and UCSB have changed the options available for authors twice. The current rules are the simplest.

For samples and analysis, see  https://wiki.library.ucsb.edu/display/repos/ETD+Sample+Files+for+DCE

**Comment by val99erie** [comment]
Some sample files are on the sandbox server at:  /opt/download_root

**Comment by val99erie** [comment]
The possible access levels that are described in the wiki page by Chrissy are:
  1. Open access
  2. Campus use only
  3. Embargo

**Comment by mark-dce** [comment]
Yes, for now let's assume that there's a "Restricted" level:
* Restricted - only admins
* UCSB-only - only logged in
* Public Access - anyone without logging in

"Campus Use Only" is orthogonal to these (i.e. something could be public access (no-login-required) and campus-use-only.

"Embargo" is also not strictly a level itself.  Embargo would mean that the items in a more restrictive state and should transition to a less restrictive state at some defined date.

**Comment by val99erie** [comment]
Question: 

@mark-dce had mentioned that the "on campus" behavior is separate from the access policy behavior.

In Chrissy's [example data](https://wiki.library.ucsb.edu/pages/viewpage.action?title=ETD+Sample+Files+for+DCE&spaceKey=repos) all of the records in "batch 3" are marked as "campus use only" after the embargo lifts.  I assume that means that during the embargo, the records should be "admin only" access, but then what access policy should they be set to after the embargo?

**Comment by val99erie** [comment]
See this page:
https://wiki.library.ucsb.edu/pages/viewpage.action?title=ADRL+2.0+Access+Policies&spaceKey=repos

**Comment by mark-dce** [comment]
I finished the documenting / summarizing the embargo rules here:
https://wiki.library.ucsb.edu/display/repos/Embargos
