### ISSUE TITLE
ETDs show page

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#245]
Should show all the metadata and a download link for the MODS XML and the original

**Comment by jcoyne** [comment]
The metadata view has been started. We need to flesh this ticket out with specific fields to show.

Question for UCSB: 
1. I'm not seeing "Copyright" in the MARC, should that be constructed?
1. I'm not seeing "statement of responsibility" in the MARC, should that be constructed?
1. We need example MARC that has keywords and ARKs in the same record. Do you have any of those?
1. Should we parse "Advisor(s)" and "Committee members" out of `500a`

**Comment by mark-dce** [comment]
1 & 2 come from the proquest xml
4 advisor = http://id.loc.gov/vocabulary/relators/ths.html
4 for committee member use reviewer = http://id.loc.gov/vocabulary/relators/rev.html

**Comment by mark-dce** [comment]
The Initial ETD view should show

- [ ] Title
- [ ] Author (creator)
- [ ] Creation Date:
- [ ] Type of Resource: (i.e. work_type)
- [ ] Collection:
- [ ] ARK:
- [ ] Publisher:
- [ ] Place of Publication:
- [ ] Issued Date:
- [ ] Digital Origin:
- [ ] Contributing Institution:

**Comment by jcoyne** [comment]
Mark: what is the original source (from MARC) of the fields that are not yet checked off?

**Comment by jcoyne** [comment]
@mark-dce are you sure http://id.loc.gov/vocabulary/relators/dgs.html isn't a better choice for Comittee member?

**Comment by jcoyne** [comment]
Yeah, NM, rev is better.

**Comment by mark-dce** [comment]
Breaking this out into individual tickets and closing this one.

#301 Import Advisor
#302 Import committee members
#275 Crosswalk ETD properties (for remaining attributes)
