### ISSUE TITLE
ETD Metadata download

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#247]
On the show page the user can click "Download Metadata" and they will see the raw MARC or RDF (whatever we have).

**Comment by jcoyne** [comment]
Currently we don't have MODS XML. Do we need to convert the MARC to MODS? Does UCSB have an existing tool for this?

**Comment by jcoyne** [comment]
Per conversation  June 16, 2015, just provide a download of whatever metadata we have. In this case MARC

**Comment by mark-dce** [comment]
Per our further discussions about the importer, etc.  let's just provide the same turtle view you get when viewing images

**Comment by mark-dce** [comment]
done - RDF view is available
