### ISSUE TITLE
Fix the names issue desribed in Chrissy's April 30 e-mail

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#250]
Subject: Name subjects not being ingested?

**Comment by mark-dce** [comment]
Hi DCE,

I have been working on mapping some of our legacy spreadsheets to the csv template. One of the questions that just came up while doing so was if I needed to place geographic, name, and topical subjects in separate fields. I checked the sandbox, and discovered that place subjects are currently being mapped to http://purl.org/dc/terms/spatial and topics to http://purl.org/dc/terms/subject. However, when I checked an example with a name subject, I discovered that the names were not being ingested: http://sandbox.curationexperts.com/lib/ark:/99999/fk4p84ft4s

In the attached MODS record, you can see that this record includes the following two names as subjects, that are not in the associated RDF record in the sandbox

	<mods:subject>
		<mods:name type="corporate" authority="naf"
			authorityURI="http://id.loc.gov/authorities/names"
			valueURI="http://id.loc.gov/authorities/names/n87914041">
			<mods:namePart>American Film Manufacturing Company</mods:namePart>
		</mods:name>
	</mods:subject>

	<mods:subject>
		<mods:name type="personal" authority="naf"
			authorityURI="http://id.loc.gov/authorities/names"
			valueURI="http://id.loc.gov/authorities/names/n88034891">
			<mods:namePart>Minter, Mary Miles</mods:namePart>
			<mods:namePart type="date">1902-1984</mods:namePart>
		</mods:name>

For now I will leave geographics, name subjects, and topics in separate fields in the csv template. Please let me know if this is correct.

Thanks,
Chrissy
---
Chrissy Rissmeyer
Metadata Librarian
University of California, Santa Barbara, CA 93106-9010
crissmeyer@library.ucsb.edu
805-893-4149

**Comment by val99erie** [comment]
@mark-dce : How can I find out what record Chrissy is talking about?  I searched for 'fk4p84ft4s' in the sample records, but I don't find anything.

**Comment by jcoyne** [comment]
@val99erie Alicia and I nuked what was on the server, so that record now has a new id.
