### ISSUE TITLE
Import Images via CSV

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#257]

**Comment by jcoyne** [comment]
Blocked because we don't have any images to test with.

**Comment by acozine** [comment]
45 images and two CSV files have been loaded onto our sandbox server on AWS. 
/opt/csv_import/metadata contains two files - one with metadata for the collection, and one with metadata for the objects in the collection.
/opt/csv_import/images contains the TIFF file. 
First test resulted in an error - see ticket #411.

**Comment by jcoyne** [comment]
The provided CSV was broken in that it had literals rather than uris in the lc_subject column (column L)
