### ISSUE TITLE
Import Preliminary MARC record and create object

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#265]
**GIVENS**
* Downloads will be in a server directory "#{downloads_root}/etd/xml"
* Records will be in MARCXml format 
* Files will be stored one record per file - named by system id
* Valid files for import must contain
    * 100 - MAIN ENTRY--PERSONAL NAME
    * 245 - TITLE STATEMENT (NR)
    * 956  Local Electronic Location and Access - filename 
    * Records must contain ARK
* The object will be store the pegasus/aleph system ID (from the filename)
* Importer runs from the command line in the foreground for the time being

**Comment by mark-dce** [comment]
Move the processed file to either a ./done or ./failed subdirectory

**Comment by jcoyne** [comment]
presently you can do this with:
```
bundle exec traject -c traject_config.rb ../ucsb_sample_data/etd_20150612.mrc
```
