### ISSUE TITLE
Associate PDF with existing ETD object

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#266]
**ASSUMPTIONS**
* There will be an existing ETD object that has a system ID, title, creator, and primary filename
* Downloads will be in a server directory "#{downloads_root}/etd/proquest"
* The ETD object will have the PDF filename already saved.
* The PDF will be embedded in a zip file with a unique name like:  etdadmin_upload_331128.zip
* Valid files for import must contain
    * at least one PDF matching the primary file name 
    * at least one XML file matching the primary file name
* Importer runs from the command line in the foreground for the time being

**Comment by val99erie** [comment]
The way to match up the ETD record with the right zip file is by matching the filename of the PDF.

**Comment by mark-dce** [comment]
Provide some way of distinguishing between zip files that haven't been processed yet, that are done, and that have some issue (like it's missing the PDF)
