### ISSUE TITLE
Associate supplemental file(s) with existing ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#267]
Extend the existing ETD file import to attach any supplemental files included in the proquest zip file 

**GIVENS**
* There will be an existing ETD object that has a system ID, title, creator, and primary filename
* Downloads will be in a server directory "#{downloads_root}/etd/proquest"
* Supplemental files will be embedded in a zip file with a name in the format:  etdadmin_upload_331128.zip
* Valid files for import must contain
    * at least one PDF matching the primary file name 
    * at least one XML file matching the primary file name
* if the zip file contains a subdirectory, attach the files in the subdirectory to the ETD object
* Importer runs from the command line in the foreground for the time being

**Comment by val99erie** [comment]
This story might depend on #266

**Comment by mark-dce** [comment]
Good sample files would be:
*  004511621.xml +  etdadmin_upload_292976.zip 
* 004511577.xml +  etdadmin_upload_293387.zip

Each of these has multiple supplemental files attached.
