### ISSUE TITLE
Update ETD MARC data

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#269]
Extend the existing ETD Importer to parse updated marc files

**GIVEN**
* There will be an existing ETD object that has a system ID, title, creator, and primary filename
* Downloads will be in a server directory "#{downloads_root}/etd/xml"
* Importer runs from the command line in the foreground for the time being

**ACCEPTANCE CRITERIA**
- [ ] When the importer processes XML files from the downloads directory, it correctly updates existing records or creates new records with the metadata.

**Comment by val99erie** [comment]
This story is probably to just add more fields into the importer from #265

**Comment by mark-dce** [comment]
And to determine whether an object exists already - in which case the file contains data that should overwrite the existing MARC metadata; or whether there is not corresponding ETD with this system ID in which case create a new record per #265

**Comment by mark-dce** [comment]
Closing and re-writing based on better requirements
