### ISSUE TITLE
Import Publication Place

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#27]

**Comment by jcoyne** [comment]
How is placeTerm different from geographic subjects?

**Comment by mark-dce** [comment]
Where are you seeing placeTerm - in the sample data?  Is this still an issue with the additional mapping info?

**Comment by jcoyne** [comment]
originInfo/place/placeTerm

**Comment by mark-dce** [comment]
Path in MODS file:
mods:originInfo/place/placeTerm@type(text)

Predicate:
OregonDigital::Vocabularies::MARCREL.pup

Ruby name:
place_of_publication

data type:
unconstrained string
