### ISSUE TITLE
Additional logging and error handling for ETD imports

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#274]
First round, log to `<RAILS_ENV>.log`. Consider audit log and/or database in future.

Metadata files from aleph/Pegasus:
All log messages should include the system ID, the ARK, and the date.
Metadata files successfully imported: move to an "imported" subdirectory, log `"new object <system_id< located at <ARK> created on <date>" or "existing object <system_id< located at <ARK> updated on <date>"`
Metadata files that are missing required fields: log and print to STDOUT
Metadata files in bad formats/unparseable: log and print to STDOUT

ProQuest zip files:
successful import: move to "imported" subdirectory, log `"PDF file <title> added to object <system_id< located at <ARK>"`
zip files with no PDF: log and print to STDOUT
zip files with no metadata: log and print to STDOUT
zip files that do not match an existing record in Alex2: silent ignore - importer will not try to import

**Comment by jcoyne** [comment]
Seems like some of this work should be here: https://github.com/curationexperts/alexandria-v2/blob/ce3995420d61350c9b123076ca4752e21c74235d/lib/importer/factory/etd_factory.rb#L38-L44

**Comment by mark-dce** [comment]
After discussion, there's sufficient logging for now and we or UCSB will add new issues when specific logging features are identified as missing.
