### ISSUE TITLE
Author of an ETD is a string, putting that in the RDF causes a problem on indexing.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#276]
We need to either make a LocalName entry (ObjectFactoryWriter) or fix the indexer.

Then fix: https://github.com/curationexperts/alexandria-v2/blob/8201c34150a4acfbc42512cd917dcd3e91197365/lib/object_factory_writer.rb#L35-L36

**Comment by mark-dce** [comment]
Let's go with fixing the indexer if we provide a string.
