### ISSUE TITLE
Make sure you have confluence (wiki) access

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#289]
**ACCEPTANCE:**  you can log in and view this page:
https://wiki.library.ucsb.edu/pages/viewpage.action?title=ETD+Sample+Files+for+DCE&spaceKey=repos
- [x] Mark
- [x] Alicia
- [x] Val
- [x] Justin

**Comment by jcoyne** [comment]
I'm able to log into JIRA https://help.library.ucsb.edu/secure/Dashboard.jspa, but not the wiki. They must not have federated authentication there?  When I try to reset I get the message: "You cannot change the password for this user via Confluence. Please contact your system administrator."

**Comment by jcoyne** [comment]
When I go here: https://auth.library.ucsb.edu/pwm/public/ForgottenPassword it says "Directory unavailable. If this error occurs repeatedly please contact your helpdesk."

**Comment by mark-dce** [comment]
@jcoyne per an earlier message from John Ajao, please check whether you have access to the page at https://wiki.library.ucsb.edu/display/repos/Alexandria+Digital+Research+Library+Repository+Project+Home

If you have trouble logging in there, please send an e-mail to  support@library.ucsb.edu indicating the page your are trying to access and any errors you get.

**Comment by acozine** [comment]
I too can get into JIRA but not the wiki. Sent a note to support this morning.

**Comment by acozine** [comment]
They reset my password and I can log in now.

**Comment by val99erie** [comment]
I emailed support to reset my password
