### ISSUE TITLE
Download links for main ETD PDFs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#299]
ETDs should provide a download link for the primary PDF.  The link should be located underneath the metadata on the page.

Restrict access to the download link to administrators only for the time being until we implement the full embargo code.  I.E. only show the download link to administrators, make sure that non-admins with the link get an authorization error.

**Comment by val99erie** [comment]
Access is restricted because some of the sample ETD data is under embargo, so we can't publish it on the internet.
