### ISSUE TITLE
GUI editor

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#30]

**Comment by mark-dce** [comment]
@jcoyne What does this ticket mean?  There's is an edit view, so is this done and we've just got enhancement tickets to write?

**Comment by jcoyne** [comment]
@mark-dce It was among the first tickets, so it's a little vague. I'm okay with closing this and adding enhancements. On the other hand I'm pretty sure the current editor actually breaks the content if you click "update".

**Comment by jcoyne** [comment]
I fixed some of these issues with 5deb465
