### ISSUE TITLE
Import Advisor for ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#301]
attribute name: advisor
predicate:  http://id.loc.gov/vocabulary/relators/ths.html (Oargun::Vocabularies::MARCREL.ths)

**Comment by val99erie** [comment]
Which field in the metadata file is the advisor?

If I use "500a", then I get 3 advisors for this record, and 2 of them are clearly not correct:
https://github.com/curationexperts/alexandria-v2/blob/master/spec/fixtures/marcxml/SBA01004092515-AlephSRU.xml#L52-L60

Also, I see that the "500" field is called "General Note", so it seems like there might be things there that aren't meant to be advisor:
http://www.loc.gov/marc/bibliographic/bd500.html

That advisor's name also appears in field "720a":
https://github.com/curationexperts/alexandria-v2/blob/master/spec/fixtures/marcxml/SBA01004092515-AlephSRU.xml#L93-L96

But the "720" field is just a generic name field:
http://www.loc.gov/marc/bibliographic/bd720.html

So, it seems like the "720e" field is significant.  Are we only looking for certain values in "720e" to assume that the "720a" field should map to advisor?  Which value(s) are acceptable to call it a match?

**Comment by val99erie** [comment]
Here is some info that Ian forwarded from Michael Kim:

I consulted with Catherine. We agree that 720 field would be a better choice (as opposed to 500 field). 500 fields may come with advisor name(s), committee member names, in addition to other general bibliographic notes.

720e with “degree supervisor” as its designator (without quotation marks).

There is a future possibility of migrating 720s to 700s after some authority control work, but it would be a different discussion and shouldn’t be a change in the near future.

**Comment by mark-dce** [comment]
Confirmed with UCSB
Read name from 720e
use internal attribute name advisor
use predicate dgs (http://id.loc.gov/vocabulary/relators/dgs.html)

**Comment by val99erie** [comment]
After discussion, we changed the name to degree_supervisor instead of advisor
