### ISSUE TITLE
Import committee member(s) for ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#302]
attribute name: reviewer 
predicate: http://id.loc.gov/vocabulary/relators/rev.html (Oargun::Vocabularies::MARCREL.rev)

**Comment by jcoyne** [comment]
These only seem to be in the 500a (Notes) field and are not in a 720. We'll have to look for 500a fields that match the regex `/Committee members: (.*)$/`

**Comment by mark-dce** [comment]
I just confirmed with UCSB that they don't want to carry this forward in ADRL 2.0 - we can close this
