### ISSUE TITLE
When reimporting an ETD don't recreate the TimeSpan

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#311]
The created field should only have a single predicate pointing at a single TimeSpan.  Presently when reimporting, it adds a new one rather than updating the existing one.

**Comment by val99erie** [comment]
@jcoyne  "The created field should only have a single predicate pointing at a single TimeSpan" -- is that true only for ETDs, or for other records as well?  Should I put this behavior in the ETDFactory or in the base ObjectFactory?

**Comment by jcoyne** [comment]
It's that each time stamp field should only have one TimeStamp, but I'm not sure that we have this problem when we re-import Images.
