### ISSUE TITLE
Implement restrictions for "Campus Use Only"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#316]
UCSB campus addresses are:
128.111.*.*
169.231.*.*

**Comment by ilessing** [comment]
to determine if the user is On-Campus check the value of the HTTP Header: X-Forwarded-For as we use a proxy in front of our production instance of ADRL

**Comment by mark-dce** [comment]
Campus-use-only can occur in conjunctions with any other access policy: e.g.
* Campus-only + UCSB-only
* Campus-only + Public Access
* Campus-only + UC-wide Access

Like other access controls and restrictions, the metadata for the item is always available, just the object itself is restricted for viewing or downloading.

The user should get a message like "This item is restricted to campus use only.  For more information, please contact the library."  Please implement this using i8ln so there's an easy way for UCSB to change this text.

**Comment by mark-dce** [comment]
Superseded by #357 and #362
