### ISSUE TITLE
Import ARK from marc field 028

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#317]
UCSB will be updating marc records to have the vanilla ARK in field 028.

This story is blocked until the updates have been completed.

Once updates are done, update our code to read from 028 instead of parsing out of the url in 856u.

**Comment by ilessing** [comment]
Ana corrected where the ARK will be stored in our system.  It will be in the **024** field not the 028 field.

We have a Jira ticket on this issue if you need details refer to  [DIGREPO-372](https://help.library.ucsb.edu/browse/DIGREPO-372)

**Comment by mark-dce** [comment]
Fixed in #331
