### ISSUE TITLE
How should we index date ranges

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#32]
```xml
<mods:originInfo>
	<mods:dateCreated encoding="iso8601" point="start" qualifier="approximate" keyDate="yes">1910</mods:dateCreated>
	<mods:dateCreated encoding="iso8601" point="end" qualifier="approximate">1919</mods:dateCreated>
</mods:originInfo>
```

**Comment by acozine** [comment]
Good question. Let's use a date slider - see ticket #63.

**Comment by jcoyne** [comment]
The question has to do with how they should be sent to solr, not how to display the UI.

**Comment by mark-dce** [comment]
dateIssued start & end both need to be preserved for display in single item view
dateCreated start & end both need to be preserved for for display in single item view
earliest_date should be the earliest date found in either date_issued or date_created
latest_date should be the latest date found in either date_issued or date_created

if only dateIssued or dateCreated exist and they are a single date, set earliest_date=latest_date

sort should be on earliest_date

if only year is provided, assume January 1st when comparing against calendar dates

**Comment by jcoyne** [comment]
Do dateCreated start & end need to be differentiated with dateIssued start & end? That question was added to the metadata spreadsheet. I think we need that answered before this can proceed.

**Comment by mark-dce** [comment]
@jcoyne - yes, that's what I was trying to say.  Keep everything separate, the distinctions are significant and will occur more in future data.  So, dateCreated and dateIssued need to be differentiated.  In future datasets, both will be present on some items.  We should accommodate them both potentially being point dates or ranges.  We should accommodate the point dates or ranges both being expressed as Years or Calendar Dates.
