### ISSUE TITLE
View Access Control Metadata

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#329]
Administrators should have a view that shows:

* The currently assigned access policy for an object
* Whether an embargo is set (i.e. is there an an embargo end-date)
* The post-embargo access policy

The page should be viewable by 
* Metadata Admins
* Rights Admins
* Super Admins (if we implement them)

The metadata should not be editable by Metadata admins - see #330.

For more detail about groups see https://wiki.library.ucsb.edu/display/repos/ADRL+2.0+Access+Policies#ADRL2.0AccessPolicies-policies#groups

**Comment by jcoyne** [comment]
Ensure this works for Images and ETDs

**Comment by mark-dce** [comment]
We'll add a partial to the main view page that's restricted to admins.

**Comment by mark-dce** [comment]
One of the differences between ADRL and Absolute is that absolute only has 3 total possible access levels "Private" "CWRU Only" and "Public".  So, it's relatively easier to make badges for each and list all possible options on pages like the edit access policy view for Absolute.  ADRL also has different level of administrator users some with read-only needs to see embargo data, some with full update rights.  So, I'm not sure the same view could work for ADRL that's in Absolute.

Here's what I think we basically need:
![adrl2 - 329 view embargo](https://cloud.githubusercontent.com/assets/3064318/8913223/490ae472-345d-11e5-8a57-4c84c51a6204.png)

Here's the issues I see with the current Absolute view - mostly that Absolute assumes 3 fixed levels of access and ADRL currently has 7 with the potential of adding more:
<img width="862" alt="adrl2 - 329 view embargo - absolute comparison" src="https://cloud.githubusercontent.com/assets/3064318/8913376/64cf9094-345e-11e5-85ed-ccf85cb4c2f8.png">

**Comment by mark-dce** [comment]
The base view in Absolute does not show me when an item is actually under embargo:

<img width="817" alt="adrl2 - 329 view embargo - absolute base view" src="https://cloud.githubusercontent.com/assets/3064318/8917732/80148952-3479-11e5-8fb8-6ebe9005e102.png">

Even though

<img width="820" alt="adrl2 - 329 view embargo - absolute work embargo view" src="https://cloud.githubusercontent.com/assets/3064318/8917777/c3a5db6c-3479-11e5-8477-43b3a248907c.png">

**Comment by mark-dce** [comment]
Superseded by #380 & #381
