### ISSUE TITLE
Implement Development Environment groups

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#334]
Set up the following roles in the development environment initializers to mimic LDAP and Shibboleth provided groups in staging and production:

- [ ] Super Administrator - super_admin
- [ ] Rights Administrator - rights_admin
- [ ] Metadata Administrator - metadata_admin
- [ ] UCSB, on-Campus - ucsb_user_on_campus (pseudo-group. Has an on campus ip and in the UCSB group)
- [ ] UCSB - ucsb
- [ ] UC-Community - any_uc
- [ ] Public, on-Campus - any_user_on_campus (pseudo-group. Has an on campus ip)
- [ ] Public - public

For additional details see https://wiki.library.ucsb.edu/display/repos/ADRL+2.0+Access+Policies#ADRL2.0AccessPolicies-groups

**Comment by mark-dce** [comment]
"On campus" is dynamic - the same user login could be on_campus or not depending on where they login from.  Can we handle this with can-can roles, or do we need to do something else?

**Comment by acozine** [comment]
The LDAP groups and users are ready for this ticket. See #320 for details on the group members.

**Comment by mark-dce** [comment]
Closed by #320
