### ISSUE TITLE
Add "dissertation" field to ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#338]
Ruby name | Predicate | MARC source
--------------|--------------|------------------
dissertation_degree | RDF::Vocab::Bibframe.dissertationDegree | 502.b
dissertation_institution | RDF::Vocab::Bibframe.dissertationInstitution | 502.c
dissertation_year | RDF::Vocab::Bibframe.dissertationYear | 502.d

**DISPLAY HELPER**
dissertation = dissertation_degree + "--" + dissertation_institution + ", " + dissertation_year

**SAMPLE**
```xml 
  <datafield tag="502" ind1=" " ind2=" ">
      <subfield code="b">Ph.D.</subfield>
      <subfield code="c">University of California, Santa Barbara</subfield>
      <subfield code="d">2014.</subfield>
    </datafield>
```
should be displayed as
Ph.D.--University of California, Santa Barbara, 2014

**Comment by jcoyne** [comment]
Closed by #419
