### ISSUE TITLE
On Campus Groups

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#357]
- [x] When I am logged-in and on-campus* I should be assigned to the ucsb-on-campus group
- [x] When I am not logged in and on-campus, I should be assigned to the public-on-campus group

*on-campus means my request is coming from an IP address in one of the approved ranges

**Comment by mark-dce** [comment]
UCSB campus addresses are:
128.111..
169.231..

These should probably go in a config file so we can change them for local testing.

**Comment by val99erie** [comment]
I don't think we'll be able to use groups to achieve the on-campus permissions.

I think we need to change the acceptance criteria to something like this:

For a file with access policy of "UCSB on campus":
- [ ] When I am logged in and on campus, I can download the file
- [ ] When I am logged in, but off campus, I cannot download the file
- [ ] When I am not logged in, either on- or off-campus, I cannot download the file

For a file with access policy of "Public on campus":
- [ ] When I am logged in and on campus, I can download the file
- [ ] When I am logged in, but off campus, I cannot download the file
- [ ] When I am not logged in, and on campus, I can download the file
- [ ] When I am not logged in, and off campus, I cannot download the file

**Comment by val99erie** [comment]
Actually, I'm not sure whether or not groups will work -- I thought we'd end up with a nil problem.  I'll give it a try with groups first.

**Comment by val99erie** [comment]
I was able to implement it using groups.
