### ISSUE TITLE
Insufficient Access rights Messages for download links

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#359]
Use I18n to display messages for the following cases:

- [x] User is not logged in and the item is restricted to "Campus-Only, Open Access"
message: *This item is restricted to on-campus access only, please contact a librarian if you need additional assistance.*

- [x] User is not logged in and the item is restricted to "Any UC (Shibboleth) Login"
message: *This item is restricted to logged-in University of California users only, please login or contact a librarian if you need additional assistance.*

- [x] User is not logged in with a UCSB account and the item is restricted to "UCSB Logins Only"
message: *This item is restricted to UCSB users only, please login or contact a librarian if you need additional assistance.*

- [x] User is not logged in with a UCSB account and the item is restricted to "UCSB Logins Only"
message: *This item is restricted to UCSB users only, please login or contact a librarian if you need additional assistance.*

- [x] User is not logged in with a UCSB account or is not on campus and the time is restricted to "Campus-Only, UCSB Logins Only"
message: *This item is restricted.  You must be a UCSB user and can only access this item on campus.  Please contact a librarian if you need additional assistance.*

- [x] Item is restricted to "Discover Only"
message: *This item is restricted and not available for digital download.  Please contact a librarian if you need additional assistance.*

**Comment by mark-dce** [comment]
Users should either see download links for all files attached to an ETD or see a single copy of the message above.

<img width="973" alt="adrl2 - 359 - user with access to download links" src="https://cloud.githubusercontent.com/assets/3064318/8913911/7870a590-3461-11e5-8960-06eb2900f139.png">

<img width="979" alt="adrl2 - 359 - user without access" src="https://cloud.githubusercontent.com/assets/3064318/8913910/7870bcba-3461-11e5-9c16-1811b3bba53e.png">

**Comment by jcoyne** [comment]
Mark: where does that "Access: UC Santa Barbara Only" come from. It seems you've only supplied the not authorized messages.

**Comment by jcoyne** [comment]
Also, how does this combine with #381?

**Comment by jcoyne** [comment]
Why show the table headers (e.g File(Download), Description) if we aren't going to show the rows when we suppress links?

**Comment by jcoyne** [comment]
The current site shows the attachements even if you don't have access to them:
http://alexandria.ucsb.edu/catalog/adrl:f3bg2kw5

**Comment by mark-dce** [comment]
Looking at the mockups UCSB originally provided, it looks like they envisioned showing the filenames (and reduced fidelity) images for items that were restricted.  

Still, the current behavior seems pretty unkind to the user: provide a link, have the user click-on it, take them to a login screen, have them login, then get re-directed to a screen that says they don't have access.

So, I propose that we leave the download links as is (or more kindly, show them, but disable them unless the user has appropriate access rights) AND show one of the messages above if they don't have sufficient privileges to access the download.

If the user is not currently logged in with sufficient access privileges to download a document,
- [ ] they should get one of the messages above 
- [ ] they should see the list of files
- [ ] download links for the files should be disabled

**Comment by mark-dce** [comment]
Ticket #381 is meant to cover the cases where the user is logged in and has sufficient access rights.
