### ISSUE TITLE
Refresh MARC fields for a single ETD from command line

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#361]
If the importer is called with a MARCxml file corresponding to an existing ETD (i.e. the system number in the MARC matches the system number for and existing ETD), the importer should overwrite existing metadata with the metadata contained in the MARCxml record.

**Comment by jcoyne** [comment]
Is this fixed by https://github.com/curationexperts/alexandria-v2/commit/f6899afaaa6690a21b4c051fa0686254d83ce9b3 ?

**Comment by mark-dce** [comment]
I've confirmed that re-importing a MARC record overwrites any values from the MARC record, but it doesn't clear values that are absent in the new MARC record.

**STEPS TO DUPLICATE**
1. Import some etd MARC record and note it's ARK
2. Open a rails console and look up the etd by ARK
3. Edit the title and add a location
    1. etd.title = ["Kilroy was here"]
    2. etd.location = [RDF::URI('http://id.loc.gov/authorities/subjects/sh85072779')]
    3. etd.save
4. Reimport the original MARC record

**EXPECTED RESULTS**
* The title should be reset to the correct title.  
* The location should be cleared

**ACTUAL RESULTS**
* The title is reset correctly
* The location is persisted, even though it didn't exist in the MARC record

**Comment by jcoyne** [comment]
Location is not a field that is imported by the MARC importer. Perhaps this is the problem?

**Comment by mark-dce** [comment]
Ok, it does appear that the importer overwrites any field that's defined in Traject.  Since it's probably going to be hard to tell what fields might or might-not be populated by the proquest importer, that's probably sufficient.  (I was thinking we could just clear the full object before re-importing, but things like keywords are coming from a different source and need to be retained.)
