### ISSUE TITLE
Check HTTP headers for IP in case of proxying

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#362]
to determine if the user is On-Campus check the value of the HTTP Header: X-Forwarded-For as we use a proxy in front of our production instance of ADRL

For testing & demos, we should fall back to the existing check if the  X-Forwarded-For header is absent or doesn't contain an IP

**Comment by val99erie** [comment]
See Ian's comment in #316

**Comment by jcoyne** [comment]
This can be done with the `ActionDispatch::RemoteIp` middleware (already in our stack).  See http://api.rubyonrails.org/classes/ActionDispatch/RemoteIp.html

**Comment by jcoyne** [comment]
we may need to set `Rails.application.config.action_dispatch.trusted_proxies = "1.2.3.4"` on production.

**Comment by val99erie** [comment]
It looks like Rails is already invoking it by default.

It calls:  ```ActionDispatch::RemoteIp::GetIp.calculate_ip```
when you call this method in the application_controller:  ```request.remote_ip```

I was able to trigger on/off campus behavior by configuring trusted IP addresses and then modifying the ```X-Forwarded-For``` on my requests.

So, I think the only thing that is left is to properly configure the trusted proxy IPs in the production environment.  (Setting ```config.action_dispatch.trusted_proxies``` in the ```production.rb```)
