### ISSUE TITLE
Clear MARC fields that are blank in the source XML (when reimporting / updating)

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#366]
* Re-running the MARC importer should clear any metadata fields that are not present or empty in the current import file.

(right now, fields retain the data they had in them from previous imports)

**Comment by mark-dce** [comment]
Currently, tract does not appear to clear existing content in fields it imports.

I've set up two sample files to use for testing:
* **batch1.xml** - has un-editied data for (4) MARC ETD records
* **batch1_w-o_descriptions.xml** - has description and degree supervisor removed; title and extent modified [added content in brackets]

To test
1. Use traject to import **batch1.xml** you should see ETDs for authors "Flowers", "Gonzalez", "Kim", and "Rossol" 
2. Check the ETDs in the UI or rails console; they should include description and degree supervisor data
3. Use tract to import **batch1_w-o_descriptions** 
4. Check the same ETDs; the titles should be prefixed with "[Moded]", the extent should have "[PDF]" appended, descriptions and degree supervisors are missing in the input file
**EXPECTED BEHAVIOR:** the description should be empty
**ACTUAL BEHAVIOR:** the description persists from the original import

*NOTE:* I realize removing the description is unlikely and this is a contrived example, but it's easy to see and quick to check via the UI.  The overall behavior should be enforced - if field data is removed in Pegasus, that field should be updated correspondingly in Alexandria.

**Comment by jcoyne** [comment]
You have removed the fields, not cleared their value.  If you clear their value, rather than remove the field it does work.

**Comment by jcoyne** [comment]
Because some metadata fields come from MARC and some come from Proquest, it will be a maintenance headache to manage all the fields that we are expecting to be present in MARC (but aren't).  We can do it for how we understand things presently, but this list would have to be updated for every new field we add in the future. I suspect it's likely the programmer will overlook that.

**Comment by mark-dce** [comment]
@jcoyne Thanks for doing this.  I do understand the code maintenance issue this opens.  Would it be any easier to just 'keep' the fields that come from proquest - since they are many fewer and less likely to change over time.  If you have other ideas, I'm also open to any other ways that we can allow UCSB admins to clear fields if they got erroneously imported from Pegasus.
