### ISSUE TITLE
Sample MODS for ETD Collections

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#367]
- [ ] Set up sample MODS file to import with the ETD Collection metadata.  
- [ ] Send the sample to UCSB for them to edit as they desire.

**Comment by ilessing** [comment]
Michael Kim will likely be the one to provide text for the Collection level record.
We also have an issue in our Jira system for this: 
https://help.library.ucsb.edu/browse/DIGREPO-371

**Comment by mark-dce** [comment]
Created https://github.com/curationexperts/alexandria-v2/blob/master/spec/fixtures/mods/etd_collection.xml

I need help getting it imported in my development environment and on the sandbox.
