### ISSUE TITLE
How to handle "Series" for items in collections?

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#37]
The sample data file cusbspcsbhc78_100239.xml has 2 entries for "relatedItem":
```
<mods:relatedItem type="host">
  <mods:titleInfo>
    <mods:title>Joel Conway / Flying A Studio photograph collection </mods:title>
  </mods:titleInfo>
  <mods:identifier type="local">SBHC Mss 78</mods:identifier>
</mods:relatedItem>

<mods:relatedItem type="series">
  <mods:titleInfo>
    <mods:title>Series 4: Glass Negatives</mods:title>
  </mods:titleInfo>
</mods:relatedItem>
```
For this sample, the Image should belong to the "Joel Conway / Flying A Studio photograph collection".

Question:  Should we do anything with the 2nd entry, "Series 4: Glass Negatives"?  If so, what metadata field should it map to?

**Comment by val99erie** [comment]
In Chrissy's email, she talked about linking to the collections and series from their finding aid site:
http://www.oac.cdlib.org/findaid/ark:/13030/kt1j49r67t/

> One of the reasons I included this in the digital object metadata is to facilitate linking from our finding aids on the Online Archive of California to the digitized objects in ADRL without the need to add/maintain hundred or thousand of links (or add/maintain object level description to the finding aid).

**Comment by val99erie** [comment]
Q:  Do you want users to be able to facet or search by series?

Chrissy's answer:
> It would probably be strange to have users be able to facet by series (unless the faceting could be contextual to a specific collection), but the ability to search would be good. My (possibly incorrect) assumption was that the link from the finding aid would resolve to essentially a canned search for a specific series in a specific collection.

**Comment by val99erie** [comment]
In the document called UCSB_ADRL_Project_Phase_2-Features_and_Functions_2.pdf there is a wireframe on page 5 that shows a collection with some series.  Take a closer look at that document.

**Comment by mark-dce** [comment]
Add the "series" field to the mods parser.

* [ ] Imports series for an Image
Does not apply to at the collection level

Field in MODS file:
mods:relatedItem@type(series)/titleInfo/title (nested inside of collection)

RDF Predicate:
OregonDigital::Vocabularies::OREGONDIGITAL.seriesName

Field type:
string
