### ISSUE TITLE
Need new sample file for etdadmin_upload_295017.zip

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#375]
This appears to be a copy that's been unzipped and re-zipped on a mac, the contents do not match other files we've seen.

**Comment by jcoyne** [comment]
Seem that `etdadmin_upload_295017.zip` is a bad file with extra Mac files in it. Other files do not have that.

```
$ unzip -l etdadmin_upload_295017.zip
Archive:  etdadmin_upload_295017.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  06-17-2015 22:47   etdadmin_upload_295017/
 30800004  06-14-2014 06:37   etdadmin_upload_295017/Calvo_ucsb_0035D_12211.pdf
     8228  09-04-2014 14:05   etdadmin_upload_295017/Calvo_ucsb_0035D_12211_DATA.xml
        0  06-18-2015 17:19   __MACOSX/
        0  06-18-2015 17:19   __MACOSX/etdadmin_upload_295017/
      221  09-04-2014 14:05   __MACOSX/etdadmin_upload_295017/._Calvo_ucsb_0035D_12211_DATA.xml
---------                     -------
 30808453                     6 files
```

**Comment by jcoyne** [comment]
A good file looks like this:
```
$ unzip -l etdadmin_upload_259849.zip
Archive:  etdadmin_upload_259849.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  06-18-2015 15:33   etdadmin_upload_259849/
 50203435  01-10-2014 20:15   etdadmin_upload_259849/Holland_ucsb_0035D_12022.pdf
     6738  04-30-2014 19:02   etdadmin_upload_259849/Holland_ucsb_0035D_12022_DATA.xml
---------                     -------
 50210173                     3 files
```

**Comment by ilessing** [comment]
The original does not have the MACOSX metadata in the zipfile.  I just checked it.  (see below)  So likely the copy DCE is working with got modified somewhere along the line.  Files arriving from Proquest should not include any MacOS metadata.
```
$ unzip -l etdadmin_upload_295017.zip
Archive:  etdadmin_upload_295017.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     8228  2014-09-04 07:05   Calvo_ucsb_0035D_12211_DATA.xml
 30800004  2014-06-13 23:37   Calvo_ucsb_0035D_12211.pdf
---------                     -------
 30808232                     2 files
```

**Comment by ilessing** [comment]
Let me know if you want a fresh clean copy of the file:  etdadmin_upload_295017.zip

**Comment by mark-dce** [comment]
@ilessing I just checked our copy which I got from Chrissy's wiki page: https://wiki.library.ucsb.edu/display/repos/ETD+Sample+Files+for+DCE 
The version zipped up in Batch 2-1 has the problem.

So, yes, please send us a new copy (or attach it to that page and let me know)

**Comment by ilessing** [comment]
I uploaded it to your demo server at /home/ian

**Comment by mark-dce** [comment]
Once it's moved we will need to re-import 004511568.xml.  Re-import might not wipe out the bad file attachments - so we should delete ark 48907/f31n7z8g - check that it's author is Calvo

**Comment by acozine** [comment]
I found the file, moved it into /opt/download_root/marc/, and reingested the correct version. I kept a copy of the broken one, it's called etdadmin_upload_295017.zip.borked.
