### ISSUE TITLE
ETD download links UI

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#388]
Users should either see a download link if they meet the access criteria, or get a message as described in #359 if they aren't logged in with the necessary rights.

## Users logged in with the necessary credentials
<img width="863" alt="adrl2 - 388 - download with necessary authorization" src="https://cloud.githubusercontent.com/assets/3064318/8965387/c63c2d0e-35f0-11e5-8be0-910778948ec6.png">

## Users not logged in or without the necessary credentials
<img width="858" alt="adrl2 - 388 - download without necessary authorization" src="https://cloud.githubusercontent.com/assets/3064318/8965399/d9823b1a-35f0-11e5-843d-143dcc73df8b.png">

**Comment by val99erie** [comment]
This might be blocked by #333
