### ISSUE TITLE
When unauthorized and going to the editor, redirect away

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#40]
As a non-administrator or a non-logged-in user, when I hit a URL I'm not authorized to see (e.g. the edit page for an object - http://sandbox.curationexperts.com/records/cusbspcmss36_110113/edit), I should not see the famed "Something Went Wrong" page.

**Comment by mark-dce** [comment]
We need to decide if the user should see 
1. The view page for the same object (if they have rights), or
2. A "You are not authorized to access this page." message with
    i. Redirect to the login page if the user is not logged in, or
    ii. Redirect to the main catalog route if the user is logged in
3. OR, some other specified behavior

**Comment by mark-dce** [comment]
Not a big enough problem to merit the work.  Will communicate within the admin team how to identify and avoid this issue.
