### ISSUE TITLE
Should users be able to sign up?

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#400]
If I visit this page:
http://sandbox.curationexperts.com/users/sign_up

I get an error message because there is a problem displaying the view.

What should be the correct behavior?  We should disable that route entirely, right?  Since we are assuming that all signed in users are valid UCSB users, we don't want someone to be able to create their own account.

We should either fix that broken view or else not allow that route at all.

**Comment by mark-dce** [comment]
We should remove the sign-up link and disable the sign-up route.

**Comment by jcoyne** [comment]
remove these routes:
```
       user_registration POST   /users(.:format)                     devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
                         PATCH  /users(.:format)                     devise/registrations#update
                         PUT    /users(.:format)                     devise/registrations#update
                         DELETE /users(.:format)                     devise/registrations#destroy
```
