### ISSUE TITLE
Change label on local names

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#401]
Current label on the local name view page says "FOAF Name".
Change this to say "Name".
see, for example, 
http://sandbox.curationexperts.com/catalog/b6baaf1b-401f-48ae-b879-44a68e6e449b
Screenshot:
![screen shot 2015-07-31 at 7 08 41 pm](https://cloud.githubusercontent.com/assets/879121/9019792/ac2e6c74-37b7-11e5-81ea-efff52bdf350.png)

**Comment by mark-dce** [comment]
The label "FOAF Name" shows up in index, show, and edit views for local people authorities.
