### ISSUE TITLE
Who can view collections page?

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#404]
If I am not logged in, and I visit:
http://sandbox.curationexperts.com/collections
I get access denied.

Is that the correct behavior?

**Comment by val99erie** [comment]
Do we need to set an admin_policy_id on the collections themselves?

**Comment by mark-dce** [comment]
Everyone should be able to see the collections index page - i.e. it should be public access.  We haven't had any input from UCSB yet about whether any full collections should be restricted in any way, so let's assume 
* that the route should be visible to all users (including unauthenticated sessions)
* that collections themselves should have a "Public Access" access policy applied
