### ISSUE TITLE
Disable turbolinks on 'Access & Embargo' in toolbox

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#408]

**Comment by jcoyne** [comment]
Why?

**Comment by mark-dce** [comment]
It takes a really long time to load the edit form so the page and looks broken - I kept clicking the link and nothing happened...

**Comment by mark-dce** [comment]
<img width="802" alt="adrl2 - 408 - disable turbolink" src="https://cloud.githubusercontent.com/assets/3064318/9092919/b22824e8-3b6e-11e5-965e-25899f9da0ca.png">

**Comment by jcoyne** [comment]
I think the problem is that the list of access controls is being loaded from Fedora which is a very slow operation. We should instead have that list loaded from solr, or at least cached.

**Comment by mark-dce** [comment]
I had figured as much - I was just looking for a superficial 10-minute fix. I'm assuming indexing things into Solr is a longer fix - especially since we should fix http://sandbox.curationexperts.com/embargoes at the same time.

So, is it reasonable to just do this as a cosmetic fix for now and do the larger indexing story later, or can we do the indexing fix now and do everything else on schedule too?

**Comment by jcoyne** [comment]
It'll still be slow if we turn off turbolinks, you'll just see the "loading" spinner.  So either way the "page being slow" is what really needs fixing.

**Comment by mark-dce** [comment]
No, I really was just looking for an indication that the page is actually loading.  I understand that it will still be slow, and I'm OK with that.
