### ISSUE TITLE
Collection show page - pagination

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#41]
Pagination doesn't seem to be working on collection show page.  Investigate.

**Comment by acozine** [comment]
hydra-collections does not currently support pagination
https://github.com/projecthydra-labs/hydra-collections/blob/master/app/controllers/concerns/hydra/collections_controller_behavior.rb#L135
Justin's approach: make changes locally to collections controller, then when it works do a PR to hydra-collections
