### ISSUE TITLE
"UC users only" should appear in list of access policies

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#410]
On the screen below, I should have the option to set the access policy and the post embargo policy to "UC users only"

**Comment by mark-dce** [comment]
I think this got fixed in PR #405 while I was testing... will re-deploy and check

**Comment by mark-dce** [comment]
nope - looks like this is still missing after deploying 54a629c1c28a248501fd3bac4e9e4adb90637e92

**Comment by jcoyne** [comment]
Is there supposed to be a picture attached to this?

**Comment by jcoyne** [comment]
@mark-dce I can't duplicate this. Please re-test.

**Comment by mark-dce** [comment]
This was probably because I didn't know to run ensure_admin_policys_exist after I redeployed and before I tested for this ticket.  I'll test again and I suspect you're right that it's fixed.

**Comment by mark-dce** [comment]
I re-deployed and checked admin policies were reloaded.  Everything looks great.
