### ISSUE TITLE
Hook up the sort by widget

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#42]
Which fields should we be able to sort by?

**Comment by acozine** [comment]
Sort by:
Creator - ascending/descending
Year - ascending/descending
Relevance

**Comment by jcoyne** [comment]
@acozine Which date should we use "issued", "latestDate", or "earliestDate" or something else?

I propose we use "issued" if it's present, then "earliestDate" if it's present.

**Comment by acozine** [comment]
We've asked UCSB for a priority list of the available date fields for display (i.e. a list that says, if there's a dateIssued, show that in the field labelled "Date"; if dateIssued is nil, show earliestDate; if that's nil too, show latestDate; etc.) - we'll use that list for sorting as well. If changing the order is no big deal, then let's go ahead and build it in the order you suggest. If it's time-consuming to change, we can wait on this ticket for now, and I'll follow up with UCSB by Wednesday.

**Comment by mark-dce** [comment]
To clarify - I think the priority order or preferredDate is for sorting and faceting.  Possibly also use for  index listing date.  Single item display should display all available (populated) date terms.  Search should search across all date terms for matches.
