### ISSUE TITLE
Sort by "key" date

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#43]
E.g.
```xml
			<mods:dateIssued encoding="iso8601" keyDate="yes">1925</mods:dateIssued>
```

**Comment by jcoyne** [comment]
There's no way to do this in MODS RDF. Can we confirm this is important to UCSB?

**Comment by mark-dce** [comment]
RESOLVED: since date sorting can be handled in other ways, keyDate does not need to be maintained.  Per discussion at [Sprint #3 Demo](https://docs.google.com/a/curationexperts.com/document/d/1udeclOWD1dhDNd8TySSOG8MjEcQoHG0OtlzXVQqLrOc/edit#).
