### ISSUE TITLE
Create local subjects for strings in CSV import

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#434]
for fields where the CSV importer expects a URI, but the csv has a string, create a new local subject entry and save the URI for the local subject in the record.

DCE issue for tracking development against [DIGREPO-442](https://help.library.ucsb.edu/browse/DIGREPO-442)

**Comment by mark-dce** [comment]
for fields where the CSV importer expects a URI, but the csv has a string, create a new local subject entry and save the URI for the local subject in the record.

**Comment by mark-dce** [comment]
If this will take more than a half day, we should let them know we need to postpone this work for future scope.

**Comment by jcoyne** [comment]
We can't do this because we don't know if the string is a Person name, Corporate name or Topic.

**Comment by mark-dce** [comment]
Could we assumed that any string supplied were a 'Topic'?  If a name (Personal or Corporate) were needed, the person doing the ingest would need to create a local name ahead of time and supply the URI instead of a string.  Would that resolve the ambiguity?

**Comment by mark-dce** [comment]
Corresponds to Jira Ticket https://help.library.ucsb.edu/browse/DIGREPO-442
