### ISSUE TITLE
ETDs not consistently added to ETD collection

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#442]
See screenshot below from sandbox.  I've have similar behavior in my development environment - imported 100 ETDs, show 100 objects with Format = ETD, only 98 objects in collection "Electronic Theses and Dissertations"

**STEPS TO REPRODUCE**
Import any larger batch of ETDS???
Sandbox results came from importing `234-etds.xml` and `all-etds.xml` in /opt/download_root/marc

<img width="1171" alt="adrl2 - 442 - etds not being added to collection" src="https://cloud.githubusercontent.com/assets/3064318/9153601/5133350e-3e27-11e5-8247-bae257dc2721.png">

**Comment by mark-dce** [comment]
To clarify -
LOCAL: I imported all-etds.xml on my local system with a clean repo and got 100 etds imported (expected because of the SRU encapsulation in the file), but only 98 members in the "Electronic Theses and Dissertations" Collections

SANDBOX: I imported 234-etds.xml on sandbox and got 235 etds (I had imported one single test ETD first) but only 185 members in the "Electronic Theses and Dissertations" collection.

**Comment by jcoyne** [comment]
Multiple threads were updating the membership on the collection at the same time. So, when we turned of threads in #439, this was also fixed.
