### ISSUE TITLE
Add db:seed script

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#449]
- [ ] Put this command into rake db:seeds
AdminPolicy.ensure_admin_policy_exists

- [ ] Add rake db:seeds to ansible / setup script

**Comment by val99erie** [comment]
Instead of db:seeds, consider just adding it to here:
https://github.com/curationexperts/alexandria-v2/blob/master/config/initializers/warm_cache.rb

**Comment by jcoyne** [comment]
we can probably just change `config/initializers/warm_cache.rb` to:
```ruby
 if Rails.env.production?
  AdminPolicy.ensure_admin_policy_exists
  AdminPolicy.all # warms cache
end
```
