### ISSUE TITLE
Display "circa" for approximate dates

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#45]

**Comment by jcoyne** [comment]
Only if they haven't specified a date label

**Comment by mark-dce** [comment]
If the timespan object does not have a display label, add a display label that is constructed by

* Start: use 'ca.' if the date qualifier is specified (questionable, indeterminate, etc.)
* Start: use the start date
* Range - if the end date doesn't match the start date (and is not blank)
show a range
* End: use 'ca.' if the date qualifier is specified (questionable, indeterminate, etc.)
* End use the end date
