### ISSUE TITLE
Access to local authorities

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#458]

**Comment by jcoyne** [comment]
Might be fixed by https://github.com/curationexperts/alexandria-v2/commit/9b22dfefb250bc6a14fa70a12218a96428022d25. Need to redeploy and test.

**Comment by val99erie** [comment]
I pulled the lastest code, cleared my cache, and restarted my server.  I don't see the problem anymore, but it was intermittent before, so it's hard to be sure it's gone.

**Comment by jcoyne** [comment]
Looks like it works, but I had to set the admin policy by hand  (find doesn't call initialize) for existing records.:

```
Person.first.update(admin_policy_id: "authorities/policies/public")
```

Then it works.
