### ISSUE TITLE
Import time should be flat in relation to repo size

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#459]
Currently we are seeing linear (or exponential) increases in ingest time based on the number of existing objects in the repository. 

Long-term, there needs to be an import architecture that is roughly flat in relation to overall repo size.  I.E. ingesting an item when the repo contains 10,000 objects should take roughly the same time as ingesting an item into the same repo populated with only 100 items.

**Comment by jcoyne** [comment]
This will require migrating all existing data to hydra-works. HydraWorks has a single resource that stores the order (ore aggregation proxies) vs the 1 per item that we currently have in Alexandria.

**Comment by mark-dce** [comment]
closing in anticipation of implementing curation_concerns / hydra_works
