### ISSUE TITLE
Support ingest of dates that have months or days in addition to year

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#46]
Just use the year for faceting. We need records from UCSB of this

**Comment by val99erie** [comment]
Possible examples:
* http://digital.library.ucsb.edu/items/show/17415
* http://digital.library.ucsb.edu/items/show/918

**Comment by acozine** [comment]
Standard is ISO 8601: http://www.iso.org/iso/iso8601
Examples:
2011-03-45
2010-01
1998-06-15T20:15

**Comment by jcoyne** [comment]
Sort on string (no processing). Facet on year.

**Comment by mark-dce** [comment]
general format is YYYY-MM-DDTHH:MM:SSZ
