### ISSUE TITLE
How do I demo IP restrictions

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#460]
I've updated [application_controller.rb#L41](https://github.com/curationexperts/alexandria-v2/blob/40f4fc2fb38dc7f07fa1b99926e2645ac5d24b50/app/controllers/application_controller.rb#L41) with my current IP prefix and restarted the web server, but don't see the expected change in behavior.

It would be great for the sandbox/java8 server to have the UCSB VPN in the list so that I could vpn  to "on campus"

It looks like the VPN server gives 10.x.x.x addresses (10.9.4.23 currently) since those are unroutable externally, it should be ok to add to sandbox.

**Comment by mark-dce** [comment]
Ok, this seems to work: 
1. google 'my ip' which will give back your current IP.
2. update application_controller with the prefix obtained in #1
3. restart the web server 

I'll probably need some help to orchestrate this during the demo.

**Comment by val99erie** [comment]
It's probably easier to just add a ```return true``` at the top of this method:
https://github.com/curationexperts/alexandria-v2/blob/master/app/controllers/application_controller.rb#L35
