### ISSUE TITLE
Access message is missing for on-campus, public access

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#461]
I'm accessing http://java8.curationexperts.com/lib/ark:/48907/f36d5r51 with my IP prefix added to the list of on_campus_network_prefix entries.  I can access the file as expected, but the access policy is not being displayed.

<img width="730" alt="adrl2 - 461 - on-campus public access message missing" src="https://cloud.githubusercontent.com/assets/3064318/9238987/f13c1280-411c-11e5-808f-68b890747dd1.png">

**Comment by mark-dce** [comment]
Same with other policies and embargoes - e.g.: http://java8.curationexperts.com/lib/ark:/48907/f3p55kmq

**Comment by mark-dce** [comment]
This problem has apparently been resolved by running  the following in the rails console.
```
AdminPolicy.all[1].update_index
```

Alicia and I have seen this happen twice today (first time may have been on sandbox and second on java8 machines).

**Comment by jcoyne** [comment]
The fix @mark-dce mentions is not a good way to fix this.  Any idea how to duplicate this?  Can you tell me next time we find the machine in this state?

**Comment by mark-dce** [comment]
agreed - it's a terrible fix.  I can't reproduce the issue locally.  We'll have to ask @acozine if she can think of anything.  Otherwise, we should  just write a wiki note should this occur in the future.

**Comment by mark-dce** [comment]
The problem is occurring again on the same items - here's the current screenshot of the same item shown above:
i.e. http://java8.curationexperts.com/lib/ark:/48907/f3p55kmq and http://java8.curationexperts.com/etds/f3p55kmq/access/edit

<img width="720" alt="adrl2 - 461 - recurrs" src="https://cloud.githubusercontent.com/assets/3064318/9243582/e7a3810a-4157-11e5-9b35-ae13a570bab2.png">


<img width="1002" alt="adrl2 - 461 - recurrs - access n embargo" src="https://cloud.githubusercontent.com/assets/3064318/9243584/f0e31406-4157-11e5-92d9-f65fab2276ac.png">

**Comment by jcoyne** [comment]
@mark-dce Did anyone notice if this page worked after Alicia did the last deploy just before 5? I wonder if the deploy script is messing this up.

**Comment by jcoyne** [comment]
The cache still works:

```ruby
Rails.cache.read('admin_policies')
=> [#<Hydra::AdminPolicy id: "authorities/policies/restricted", title: "Restricted access", description: nil, default_permission_ids: ["a5/63/04/f1/a56304f1-b985-413d-9f89-8229b93c5a4a", "5d/2e/4d/25/5d2e4d25-0405-4409-a4ba-eb88525139fc"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/discovery", title: "Discovery access only", description: nil, default_permission_ids: ["6d/b1/9d/ce/6db19dce-1430-40e7-a36d-11873634ce86", "e0/55/af/18/e055af18-832a-4a97-b687-3af3e75d5df1", "7d/14/aa/3f/7d14aa3f-c3be-4f8b-9d0b-2f79f2c5da28"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/ucsb_on_campus", title: "Campus use only, requires UCSB login", description: nil, default_permission_ids: ["a7/7f/46/4a/a77f464a-e53b-4129-8619-65dceb39d9b2", "e9/43/bc/85/e943bc85-26c4-42d0-a0ad-4e53f1f3f176", "a6/29/99/6d/a629996d-7783-4077-9ca5-03cdaf00dd51", "7a/93/c2/99/7a93c299-c399-441c-ad72-76b9e97c2f20"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/ucsb", title: "UCSB users only", description: nil, default_permission_ids: ["3e/5f/eb/94/3e5feb94-3b95-4575-be69-c988b876d084", "89/4b/e8/b7/894be8b7-1b55-4a51-be72-6798d6afebd5", "b0/ab/02/50/b0ab0250-ce92-42e5-a6d0-509fa63ee3e3", "d9/d8/b0/81/d9d8b081-c656-4fec-bc2a-c77d5e147f69"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/uc", title: "UC users only", description: nil, default_permission_ids: ["13/ac/af/2d/13acaf2d-cdde-4388-ad86-17fe44b1727d", "2b/25/03/ad/2b2503ad-0ee2-48cb-b4d3-5fc5fadfe8e9", "1b/44/81/25/1b448125-8c62-4574-9e8c-c6696b7038e3", "bf/32/bd/c8/bf32bdc8-324f-4d58-8099-2927c1279662", "e4/19/49/89/e4194989-a11d-487c-a7a5-490d94a7c6a2"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/public_on_campus", title: "Public Access, Campus use only", description: nil, default_permission_ids: ["4d/5d/bc/88/4d5dbc88-474b-4ccd-b6a7-eea916c9ca8c", "74/7b/c6/02/747bc602-b56a-4615-ad3a-d934b539bf75", "2c/2b/1f/40/2c2b1f40-626e-4330-bac8-f253aa99af16", "a0/98/d1/78/a098d178-0c8c-4a03-8360-4dd64c8f0f83"], default_embargo_id: nil>, #<Hydra::AdminPolicy id: "authorities/policies/public", title: "Public access", description: nil, default_permission_ids: ["2c/99/66/18/2c996618-578a-4a32-ab53-cdf3ad40d9e1", "ce/77/2a/5d/ce772a5d-2ece-4df8-8cf3-bae9e4d90788", "bc/2d/6e/3d/bc2d6e3d-b86b-41b9-9e95-fc904fcdf0c7"], default_embargo_id: nil>]
```

After I did this ^ the page started working again.

**Comment by jcoyne** [comment]
On sandbox I saw the same problem, but this time, just refreshing the page was enough to fix the error.

**Comment by jcoyne** [comment]
curiously the timestamp on the cache was right when I reloaded that page:

```
$ ls -la tmp/cache/5C1/D40/admin_policies
-rw-------. 1 deploy deploy 558842 Aug 13 12:34 tmp/cache/5C1/D40/admin_policies
$ date
Thu Aug 13 12:38:16 UTC 2015
```

**Comment by jcoyne** [comment]
It seems that deploying is what gets us to the bad state and that  `AdminPolicy.all` is enough to get it back to the good state.

**Comment by jcoyne** [comment]
This is really odd, because `AdminPolicy.all` is what is being called in the form that doesn't work.

**Comment by val99erie** [comment]
I heard that deploy script changes may have fixed this issue.  Is this still a problem, or can we close the story?

**Comment by mark-dce** [comment]
With the refactored code, this appears fixed in my development environment.  We can reopen the ticket if it reappears on the demo server, but I don't see any further action we can take for now.

<img width="750" alt="adrl2 - 461 - on-campus public access message fixed" src="https://cloud.githubusercontent.com/assets/3064318/12999013/fbb8ecbe-d10f-11e5-86fc-2dfe85ee038c.png">
