### ISSUE TITLE
Import ETD collection when setting up system

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#466]
Either automate ETD collection import or add a note to a setup wiki somewhere to import the ETD collection record.

I.E. we didn't and got this:
<img width="978" alt="adrl2 - 466 - automate etd collection setup - before" src="https://cloud.githubusercontent.com/assets/3064318/9241964/07b764ec-4140-11e5-982c-582f0d1aa0e4.png">

Then I ran 
```
mkdir tmp/mods
cp spec/fixtures/mods/etd_collection.xml tmp/mods/
RAILS_ENV=production bundle exec script/import_mods_records ./tmp/mods ./tmp
```
and the collection appeared to be created at the console, but I get an access denied error when trying to view the collection in the UI - even as an administrator.

**Comment by acozine** [comment]
The collection metadata can be imported after the objects, but it cannot be imported during an ingest of objects belonging to that collection. The object ingest stores the collection object in memory and overwrites any changes written during that time. Wait until other ingest processes are done before ingesting collection metadata.
