### ISSUE TITLE
ETD collection is not getting an admin_policy_id set

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#467]
Possibly move this line to CollectionFactory:
```
lib/importer/mods_importer.rb:      create_fedora_objects(parser.model, parser.attributes.merge(admin_policy_id: AdminPolicy::PUBLIC_POLICY_ID))
lib/importer/csv_importer.rb:        create_fedora_objects(attributes.merge(admin_policy_id: AdminPolicy::PUBLIC_POLICY_ID))
```

**Comment by ilessing** [comment]
work around is:

at ruby console... 
```
etds = Collection.where(title: "UCSB Electronic Theses and Dissertations").first  #or find it by the ID
=> <long collection object here…>
etds.admin_policy_id
=> “authorities/policies/public"
```
That should yield => "authorities/policies/public”, but if the admin policy isn’t set you get a ’nil’ instead, 
If this is the case, try this

```
etds.admin_policy_id = "authorities/policies/public"
=> "authorities/policies/public"
etds.save
=> true
```
then the collection should display in the web browser

**Comment by jcoyne** [comment]
It seems that this is no longer necessary as the ETD collection is already created.

**Comment by ilessing** [comment]
If this issue is isolated to the ETD collection then probably no further work is needed and it can be closed.
