### ISSUE TITLE
Authority Merge auto suggest provides unexpected results for authority records with multiple labels

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#478]
If I have authorities that have multiple labels, only the most recent label is displayed for auto-suggest purposes, so I get really strange looking behavior like the screenshot below.  I.E. why are "Thingy 1" and "Better Thingy" matches for the search string "Mark"?  (in fact, both those records have additional labels that contain the substring "Mark" in an additional label)  It probably makes sense to have the auto suggest check for multiple labels on the record and display the one that triggered the match.

The records used to create the screenshot are:
http://sandbox.curationexperts.com/catalog/d0748952-9a26-4b4c-bc1c-18ccc65436ad
http://sandbox.curationexperts.com/catalog/1a2dac5b-a650-44a3-ac59-6d4b5ce217a2

<img width="1108" alt="adrl2 - 478 - uri label autosuggest returns unexpected results" src="https://cloud.githubusercontent.com/assets/3064318/12175901/5beca8ca-b52a-11e5-8e2c-e7f3ef10c921.png">

**Comment by jcoyne** [comment]
It shows you the records that match your search.  It's searching for records, not for labels.  It is labeling the record with the first label it found.  This is because all the remote vocabularies have skos:prefLabel, which means a single label.

> A resource has no more than one value of skos:prefLabel per language tag

http://www.w3.org/2012/09/odrl/semantic/draft/doco/skos_prefLabel.html

We don't want to write a special way of displaying things just for our local vocabularies.

**Comment by jcoyne** [comment]
I'm not sure that Solr has a way to tell you which fields triggered a match.

**Comment by jcoyne** [comment]
See http://alexandria.ucsb.edu/qa/search/local/names.json?q=Mark  for an example of the search results that power autoselect

**Comment by mark-dce** [comment]
Ok, so the example I created was based on contrived test data and isn't likely to occur in real life.  As long as we're sure the same situation won't occur in external vocabularies, we can close this ticket.
