### ISSUE TITLE
Local Authority facets should be expanded by default

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#479]
**WHEN I DO THIS**
> <img width="398" alt="adrl2 - 479 - display local authorities" src="https://cloud.githubusercontent.com/assets/3064318/12176235/0ee69912-b52c-11e5-9cde-4a87ae55d9e2.png">

**I GET THIS**
*i.e. the facets are collapsed and I always have to click on the ">" next to "Type"*
> <img width="456" alt="adrl2 - 479 - display local authorities - current" src="https://cloud.githubusercontent.com/assets/3064318/12176527/60db964a-b52d-11e5-97ed-96b3e41d2645.png">

**DESIRED**
*i.e. expand the facts by default, preferable also sort them alphabetically*
> <img width="468" alt="adrl2 - 479 - display local authorities - expanded" src="https://cloud.githubusercontent.com/assets/3064318/12176420/0747cb08-b52d-11e5-9a41-436a04712c1e.png">

**Comment by val99erie** [comment]
For the sorting, it looks like the best we can do with default Blacklight behavior is ordering by count first, and then ordering by name second.
https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields
