### ISSUE TITLE
Add "Type of Resource" facet

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#489]
Add a facet for the field labeled "Type of Resource" (stored as work_type).

https://github.com/curationexperts/alexandria-v2/blob/master/app/controllers/catalog_controller.rb#L156

**Comment by val99erie** [comment]
@mark-dce  We already have a facet called "Type" (which facets form_of_work).  I think it's a little weird to have both "Type of Resource" and then "Type".  Do you have any strong opinion about that?  Since we are removing the "Format" facet in #490, maybe we could change the "Type" facet to "Format"?

**Comment by jcoyne** [comment]
They want to remove the existing "Type" facet.

**Comment by mark-dce** [comment]
In my notes, I wrote that they wanted 
1) to remove the facet that has values like "ETD", and "Image" that is currently labeled "Format"
2) to keep the facet that has values like "photographs", "gelatin dry plate negatives", "sheet music", and "scores" that is currently labeled "Type"
3) to add a facet that has values like "Text", "Notated Music", "Still Image" and label it "Type of Resource"

I agree that having "Type" and "Type of Resource" facets is confusing, but I think we should add "Type of Resource" (this story), remove "Format" (#490) and then show them the UI.  Then they'll have something concrete to discuss and they can decide whether to rename on of the two facets.

**Comment by val99erie** [comment]
ok will do

**Comment by val99erie** [comment]
Will need re-index
