### ISSUE TITLE
Import a collection mods record

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#49]
Display a collection landing page that explains about the collection before showing the members.  Waiting on collection mods records from UCSB

**Comment by val99erie** [comment]
from Chrissy:

I have added draft collection level records for our two demo collections to stash: https://stash.library.ucsb.edu/projects/CMS/repos/mods-for-adrl/browse/mods_demo_set

The records I created are fairly similar to those in UCSD’s digital collections site (example: http://library.ucsd.edu/dc/collection/bb4745366c)

**Comment by val99erie** [comment]
We are closing this story for now.  I'll open separate stories for the remaining metadata fields.
