### ISSUE TITLE
Don't create TimeSpans for empty dates (probably from a CSV import)

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#492]
On sandbox there are images who's created looks like this:

```ruby
image.created
=> [#<TimeSpan id: "53/ab/49/c8/53ab49c8-aa53-4b00-880a-1385eea536bd", start: [], finish: [], start_qualifier: [], finish_qualifier: [], label: [], note: []>]
```

**Comment by val99erie** [comment]
I'm not able to reproduce the problem by leaving blank fields in the CSV file.  If all the date fields are blank in the CSV file, the importer doesn't create or update a TimeSpan object. 

Do we have an example of a CSV file that has created this error?  Or, is there currently an Image in production that has this problem that I could examine?

I've also been unable to recreate that state (TimeSpan with all fields blank) using the UI.  If I delete all the values from all the date fields when I edit an Image, then submit the form, it silently refuses to update the TimeSpan object, but the other fields update properly.

So far the only way I've been able to achieve a TimeSpan with blank fields is to edit it directly in the Rails console.

**Comment by val99erie** [comment]
Sample of bad data on sandbox:  Santa Barbara postcards collection, it was a MODS import.  Many of them have a 'created' date with empty values in them.
