### ISSUE TITLE
Find secure solution for EZ-ID credentials

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#494]
The EZID test password should not be exposed here:

https://github.com/curationexperts/alexandria-v2/blob/master/config/ezid.yml.template#L5

and in  line 11

**Comment by ilessing** [comment]
Since EZID already exposes it as part of their public API documentation I don't see any reason to hide it.
http://ezid.cdlib.org/doc/apidoc.html

**Comment by acozine** [comment]
Ian says: 
Since EZID already exposes it as part of their public API documentation I don't see any reason to hide it.
http://ezid.cdlib.org/doc/apidoc.html
Closing.

**Comment by mark-dce** [comment]
@acozine  The password isn't listed in that document - it specifically says 
> All user accounts are permitted to create test identifiers. EZID also provides an "apitest" account that is permitted to create only test identifiers. Contact UC3 for the password for this account.

Therefore, I consented to Alex's request to hide this and made this ticket.
