### ISSUE TITLE
Show the public URI for authorities

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#504]
When I create a new local authority, the link in my address bar is different from the link shown on the page:

Address Bar: http://sandbox.curationexperts.com/catalog/593a2716-bef1-4319-adae-1c8e9f94b209
Shown on Page: http://127.0.0.1:8080/fedora/rest/prod/59/3a/27/16/593a2716-bef1-4319-adae-1c8e9f94b209

The link shown on the page is typically not resolvable externally.

**ACCEPTANCE**
-[ ]  show the publicly resolvable URI on the show view for local authorities

**Comment by mark-dce** [comment]
<img width="657" alt="adrl2 - 504 - authroity uris" src="https://cloud.githubusercontent.com/assets/3064318/12484511/48f040d2-c020-11e5-8bd5-37d2339d99dd.png">

**Comment by mark-dce** [comment]
This also requires and update to the importers (CSV & Mods) to de-reference the public URI to the internal Fedora URI.

**Comment by val99erie** [comment]
@mark-dce Could you describe the use-case for the CSV and Mods importers?  How would the public URIs get into the metadata files?  It would be a lot simpler if the metadata files contained the actual fedora URI.

**Comment by mark-dce** [comment]
We should never be showing end users the internal URI that begins http://127.0.0.1  That's never going t be resolvable on a client machine, so there's no way after the fact to confirm that you have the right or valid URI.

I.E.  Here's the internal URI for an authority on ucsb.curationexperts.com: http://127.0.0.1:8080/fedora/rest/prod/f0/f3/fe/31/f0f3fe31-cf22-4bb8-8211-5229ba547171
There's no way to tell what it resolves to without logging in as an administrator, randomly searching through authorities - you don't even know what type to look at with this version - until you find a match in the listings.  There is, in fact, no way to tell if this is an authority on a Production or a test system.  

Here is a different valid current local authority: 
http://127.0.0.1:8080/fedora/rest/prod/d4/3a/69/65/d43a6965-af6b-4856-b354-6bb1029ff93f
If you import this to ucsb.curationexperts.com, it will give a frustrating error, because I forgot to tell you that it's from sandbox.curationexperts.com, so there's no way to import it into ucsb.curationexperts.com.  This form also exposes implementation details that could change in future versions of fedora: 8080/fedora/rest/prod 

Here's the public URI for a different authority:
http://ucsb.curationexperts.com/catalog/5960bb7a-432f-4a2d-a28b-b6b1f453aff5
You can tell which system it lives on.  You can resolve it and confirm that you're point at the correct authority easily.  

Because the public URI is resolvable without authentication, I can easily check it.  Because it contains the unique hostname, I can easily tell which system should be able to import it successfully.

I think it makes most sense to have end-users use the public URI in all circumstances, so we should show it to them as the URI that they should be cutting and pasting into MODS and CSV files.  I know this complicates the code on our side, but I think it provides a much clearer, less error prone end-user experience.

**Comment by val99erie** [comment]
@mark-dce Yes, I understand that non-admin users should see the public URI, but MODS and CSV files will only be created by admin users, right?  If that's true, then they could paste the fedora URI into the file just as easily as they could paste the public URI.  Why add the extra level of indirection by using the derived URI instead of the real URI?

**Comment by jcoyne** [comment]
The csv files should be portable and not care if fedora is on port 8983 or 8080

**Comment by val99erie** [comment]
I guess my argument is that the fedora URI is the canonical URI, and the public URI is derived URI that isn't stored on the object.  Shouldn't the canonical URI be the one used in metadata files?  The admin users have access to that data, even if public users don't.

**Comment by ilessing** [comment]
Actually I think non-admin staff will often prepare CSV ingest files.  Our goal is to have catalogers and other metadata staff do the work with local authorities.  These users would not have access directly to Fedora.  For security and data integrity protection we want to limit direct access to ports other than 80 & 443.

**Comment by val99erie** [comment]
@ilessing Thanks for the clarification

**Comment by val99erie** [comment]
I finished the display part of the story, but I'm going to write a separate story for the importer part.  I think we need to have a discussion about what needs to be done for the importers.
