### ISSUE TITLE
Make a template file for config/appliction.yml

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#509]
Should we use a template file for config/application.yml instead of checking it directly in to githb?

I need a different download_root setting than the default for my development environment and I have to stash it or re-enter it any time I pull code:

```
 development:
   <<: *defaults
+  download_root: 'tmp/download_root'
```

Or, would it make sense to commit this as the development default?

**Comment by jcoyne** [comment]
Yes, Val and I were coming to the same conclusion earlier today
