### ISSUE TITLE
When importing, unknown rights is never cached

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#521]
When running
```
RAILS_ENV=production bundle exec bin/ingest-mods /xfer/forked-mods-for-adrl/mods_demo_set/demo_sbhcmss78_FlyingAStudios /xfer/ucsb_images/dpsstore1/special_collections/spc-flying-a/conway-2010/16bit/
```
We see this over and over in the log:

```I, [2016-01-26T18:25:17.345915 #22398]  INFO -- : Fetching http://www.europeana.eu/rights/unknown/ from the authorative source. (this is slow)```

**Comment by acozine** [comment]
May be due to redirect to http://www.europeana.eu/portal/rights/unknown.html - investigate alternate source for URI.

**Comment by val99erie** [comment]
Also look at other europeana URIs:
http://www.europeana.eu/rights/rr-f/
and
http://www.europeana.eu/rights/rr-r/

**Comment by jcoyne** [comment]
Europeana never returns lables that we can use.  We can probably fix this by forcing a skos:prefLable into Marmotta when we start up the import job.

**Comment by mark-dce** [comment]
It it looks like it will take more than half a day to fix this, let's remove it from this release and push it to the backlog for now. 

 It looks like this is really more a data error on the Europeana side that we'd be working around than it is an actual bug in the code.
