### ISSUE TITLE
Export local authorities

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#522]
Export a set of local authorities so they can be imported to a new box or environment.

-[ ] Export should be a CSV file
-[ ] Export should contain the path (ID) of the existing Authority record
-[ ] Authority labels should be in the final column(s) of the export file and repeatable.

**Comment by jcoyne** [comment]
Blocked by #504

**Comment by val99erie** [comment]
Development work is done, but this story needs testing in conjuction with story #523.

**Comment by mark-dce** [comment]
@val99erie - is there somewhere I should look for instructions on how to set up and run an export?

**Comment by mark-dce** [comment]
@val99erie - sorry I missed the README.

**Comment by mark-dce** [comment]
I wrote up additional notes at https://github.com/curationexperts/alexandria-v2/wiki/Exporting-Local-Authorities-(especially-from-remote-systems)

I was able to export authorities from our AWS server onto my local system, so I'm going to mark this as tested and closed.
