### ISSUE TITLE
Previous and Next do not function in browse by subject

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#525]
When I go to [Browse by Subject](http://ucsb.curationexperts.com/catalog/facet/lc_subject_label_sim?facet.sort=index) on the demo server, the **Previous** and **Next** links are broken.

**ACCEPTANCE**

- [ ] When I am at the beginning of the list, the *NEXT* link takes me to the second page of the list, the *PREVIOUS* link is disabled
- [ ] When I am at the end of the list, the *PREVIOUS* link takes me back a page, the *NEXT* link should be disabled
- [ ] When I am in the middl of the list, both the *PREVIOUS* and *NEXT* buttons should work
- [ ] Both the links above and below the list work correctly 
- [ ] Facet boxes give a 'more' option if there are more facets than can be shown on screen (create a new ticket for this specific issue if it's not fixed automatically by the rest of the fixes for this ticket)

**Comment by jcoyne** [comment]
They are not broken. There is only one page of results.

**Comment by mark-dce** [comment]
@jcoyne There have to be at least two pages - if you sort numerically vs. alphabetically, you'll see that there is an entry for 'Santell, Alfred, 1895-1981', 'Russell, William, 1886-1929', 'Sloman, Edward, 1883-1972' and 'Nudes' that do not show up on the first page of alphabetically sorted listings.

**Comment by jcoyne** [comment]
Yep, confirmed. I suspect this broke when we introduced CurationConcerns.
