### ISSUE TITLE
Store Notes inline using hash URI

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#527]

**Comment by val99erie** [comment]
Question:  Using [the TimeSpan commit](https://github.com/curationexperts/alexandria-v2/commit/2d83ee03b2d5272e33ceaaf98295a0a2dc2cdf89) as an example, it looks like I'm going to need to add a "note" property to the Image class.  What predicate should I use for that?

**Comment by jcoyne** [comment]
we already have a note property. https://github.com/curationexperts/alexandria-v2/blob/master/app/models/concerns/metadata.rb#L142  You need to switch the HABTM to a property.

**Comment by val99erie** [comment]
@jcoyne Ah, yes!  I missed that when I was looking for the property.  Thanks
