### ISSUE TITLE
Change "Off Campus Login" text

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#54]
The text should just say "Login," since UCSB has confirmed that all users will need to log in to see anything beyond public data. For now, hook the Login link up to /users/sign_in. Eventually we'll use the UCSB campus LDAP.

**Comment by val99erie** [comment]
If we are removing the off-campus login stuff, it's not just a text change on the form.  There is code that should also be pulled out.  Maybe we should leave this to be handled as part of the auth story:
https://github.com/curationexperts/alexandria-v2/issues/17
