### ISSUE TITLE
Handling of local authorities in importers.

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#545]
For some background discussion, see #504

TASKS:
- [x] Update CSV importer
- [x] Update MODS importer

ACCEPTANCE CRITERIA:
- [x]  If a URI is provided in either a MODS or CSV import, it is stored as-is
- [x] The turtle view of an imported work should show a publicly resolvable version of local authority URIs
- [x] Specifically check the behavior for the CSV importer when it creates a new local authority - the new work's turtle view should show the public URI for any new local authorities

**Comment by val99erie** [comment]
How does this story relate to #522 & #523.  Does #523 make this story unnecessary?

**Comment by ilessing** [comment]
Before expending effort on the MODS importer we should check with @chrissyrissmeyer    I recall her saying she didn't want to use it for future ingests.  I doubt any of the MODS metadata collections we'll be re-ingesting need local authority needs.

**Comment by chrissyrissmeyer** [comment]
@ilessing: Stop saying all the things wrong.

The existing MODS importer already has support for local authorities (and the MODS collections we would need to re-ingest do have local authorities). Also, it would be good to keep the MODS importer current as we may need to use the MODS importer for future ingests. We do plan to use the CSV importer rather than the MODS importer for our current digitization activities.

**Comment by dunn** [comment]
Will the changes here impact our workflow, or will there be other effects we should be aware of?

**Comment by johnajao** [comment]
Where are we with this issue? We need to get some additional collection ingested ASAP and was wondering when this would be resolve? Could we have some documentation on how this will impact the current workflow as well?

**Comment by val99erie** [comment]
I don't believe that this story will affect your existing workflow.  The only thing that might change is that if you had been using Fedora URIs for local authorities in your MODS or CSV files, you would have to change those Fedora URIs into the public versions of the URIs instead.

So, a URI like this:
`http://127.0.0.1:8983/fedora/rest/dev/21/94/57/49/21945749-2fcd-4748-9dc1-60d02df1e1d0`

Would need to change to this:
`http://alexandria.ucsb.edu/authorities/people/21945749-2fcd-4748-9dc1-60d02df1e1d0`
