### ISSUE TITLE
Importer should handle locations that are URIs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#547]
<img width="723" alt="adrl2 - 547 - location label instead of uri" src="https://cloud.githubusercontent.com/assets/3064318/12923262/b00c4d66-cf1a-11e5-9a19-4a96ccb7ae0a.png">

For the entire McPeak collection, the location URI isn't being handled correctly

Specifically for mss292-g00204
See the first entry in http://ucsb.curationexperts.com/catalog?utf8=✓&search_field=all_fields&q=
or the 'Location' field in this show view http://ucsb.curationexperts.com/lib/ark:/99999/fk4sn0dp4z

**Comment by val99erie** [comment]
This object is:
Accession Number:
    mss292-g00204
Collection:
    Ronald H. McPeak underwater and coastal California photographs
