### ISSUE TITLE
Not all subject labels are being shown

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#548]
For Accession Number: mss292-g00204 "Chum Salmon"

Looking at http://ucsb.curationexperts.com/lib/ark:/99999/fk4sn0dp4z, I don't see all the subject that appear to be listed in the turtle view.
http://ucsb.curationexperts.com/lib/ark:/99999/fk4sn0dp4z.ttl 

Display view shows:
"Fishes and Chum Salmon"
Turtle view shows:
```
<http://purl.org/dc/terms/subject> <http://127.0.0.1:8080/fedora/rest/prod/82/0e/b9/f4/820eb9f4-fa4a-4144-8fe9-03548bb412a6>,
     <http://id.loc.gov/authorities/subjects/sh85048726>,
     <http://id.loc.gov/authorities/subjects/sh85025487>;
```

**Comment by jcoyne** [comment]
It appears that we are not indexing local authorities:
```ruby
img.lc_subject
=> [#<Oargun::ControlledVocabularies::Subject:0x53d4b68(#<Oargun::ControlledVocabularies::Subject:0x0000000a7a96d0>)>, #<Oargun::ControlledVocabularies::Subject:0x566b1d8(#<Oargun::ControlledVocabularies::Subject:0x0000000acd63b0>)>, #<Oargun::ControlledVocabularies::Subject:0x50db5b0(#<Oargun::ControlledVocabularies::Subject:0x0000000a1b6b60>)>]
irb(main):003:0> img.to_solr['lc_subject_label_tesim']
=> ["Fishes", "Chum salmon"]
```

**Comment by jcoyne** [comment]
This should get fixed when we reference external URIs for local authorities.

**Comment by jcoyne** [comment]
This is still broken because the importer is changing pure strings into URIs of the form:
http://127.0.0.1:8080/fedora/rest/prod/bc/ea/91/54/bcea9154-41be-422a-acbd-b2534f64abb5
rather than of the form:
http://ucsb.curationexperts.com/authorities/topics/bcea9154-41be-422a-acbd-b2534f64abb5

**Comment by jcoyne** [comment]
I think #545 should resolve this problem

**Comment by val99erie** [comment]
After #545, there are still 2 problems.  You can reproduce the problem by running this import:
`bin/ingest-csv spec/fixtures/csv/pamss045_with_local_authorities.csv Image`

- [ ] Not all lc_subjects are being indexed (missing local authorities)
- [ ] For the composer field, the URIs are being indexed (instead of fetching the proper labels)

**Comment by jcoyne** [comment]
@val99erie is this because the csv importer stores the local authority with the internal rather than the external uri?

**Comment by val99erie** [comment]
![screen shot 2016-02-12 at 9 12 56 am](https://cloud.githubusercontent.com/assets/298865/13010737/0132931c-d169-11e5-902f-7b4045c9b72f.png)

**Comment by jcoyne** [comment]
Now blocked by #569
