### ISSUE TITLE
Additional Wax Cylinder Fields to Import

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#554]
**TBD**

As a starting point, make sure we can import and display the metadata displayed here: http://cylinders.library.ucsb.edu/search.php?queryType=@attr+1=1020&num=1&start=1&query=cylinder12783

**Comment by mark-dce** [comment]
Chrissy has put together a mapping of MARC fields to existing or new attributes here:
https://docs.google.com/spreadsheets/d/1pK76NWbComHoXPC_u_uVZ1DWrOtCG1JW17-WHJwaHac/edit#gid=0

Implement as many of those as possible and accumulate any unimplemented or questionable fields into a separate ticket.

**Comment by mark-dce** [comment]
attribute | marc source | comments
-------------|------------------|------------------
work_type | leader position 6 | see mapping in #488
system_number | field 001 | same as ETDs
issued |  field 008 | see detailed date notes in Chrissy's mapping spreadsheet linked above, ignore handling dates with format like 19uu - see [DIGREPO-475](https://help.library.ucsb.edu/browse/DIGREPO-475) 
langage | field 008, columns 35-37 | Map codes to "http://id.loc.gov/vocabulary/iso639-2/[code]"). If blank leave language unpopulated
issue_number | 028 (ind1="0") | use new predicate: http://id.loc.gov/vocabulary/identifiers/issue-number   Concatenate $a & $b (format = $b: $a)
matrix_number |  028 (ind1="1") | use new predicate: http://id.loc.gov/vocabulary/identifiers/matrix-number   Concatenate $a & $b (format = $b: $a)

...work in progress had to save for landing...

**Comment by jcoyne** [comment]
Fixed by c8d9873
