### ISSUE TITLE
ETD Collection record disappears after importing additional ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#558]
**NOTE**
*The import code is broken in master, you can test this story against the `ingest-etd branch` (or rebase your branch with the two commits in that branch).  I'm planning  to merge in as soon as I have a chance to talk to Alex D.*

**STEPS TO REPRODUCE**
1. Create an empty directory somewhere and copy the MODS etd collection record to it:
`mkdir tmp/download_root/etd_collection && cp spec/fixtures/mods/etd_collection.xml tmp/download_root/etd_collection`
2. Use the MODS importer to import the collection record:
`bundle exec bin/ingest-mods tmp/download_root/etd_collection/`
3. Start your server and confirm that the etd collection has been created: http://localhost:3000/collections
4. Copy 1 or more sample proquest files to an ingest directory:
`mkdir tmp/download_root/proquest-zips && cp <path_to_sample_data>/etdadmin_upload_234724.zip tmp/download_root/proquest-zips`
5. Import the ETDs:
`bundle exec bin/ingest-etd tmp/download_root/proquest-zips/*.zip`

**EXPECTED RESULT**
The collection record still appears in the repository in the list at http://localhost:3000/collections

**ACTUAL RESULT**
The collection record no longer appears after ingesting ETDs in step 5

**Comment by mark-dce** [comment]
There's a corresponding JIRA ticket for this issue, please update https://help.library.ucsb.edu/browse/DIGREPO-414 once this issue is resolved.

**Comment by mark-dce** [comment]
FWIW, the importer says that it's updating the collection in Step 5 - "  Updated collection fk48g8v627 (etds)":
```
Now ingesting...
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: already initialized constant Metadata::MARCREL
/Users/mark/Documents/workspace/_no_backup/RubymineProjects/alexandria-v2/app/models/concerns/relators.rb:2: warning: previous definition of MARCREL was here
2016-02-11T22:49:17-06:00  INFO traject (2.1.0) executing with: `-c traject_config.rb tmp/download_root/marc/MARC_1455252544.xml`
2016-02-11T22:49:17-06:00  INFO Reading from tmp/download_root/marc/MARC_1455252544.xml
2016-02-11T22:49:17-06:00  INFO    Indexer with 0 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
  Updated collection fk48g8v627 (etds)
  Updated etd f3vm49cx (004092443)
closing
2016-02-11T22:49:23-06:00  INFO finished Indexer#process: 1 records in 5.958 seconds; 0.2 records/second overall.
```

**Comment by mark-dce** [comment]
**NOTE**
*The import code is broken in master, you can test this story against the `ingest-etd branch` (or rebase your branch with the two commits in that branch).  I'm planning  to merge in as soon as I have a chance to talk to Alex D.*

**Comment by val99erie** [comment]
@mark-dce Are you saying that this bug needs development work, or that Alex already has a fix for it?

**Comment by mark-dce** [comment]
This bug needs development work.  I just fixed the bug that prevented us from running the importer on our systems in 8e7927914f9f8103e5cb68e9d1760d7dae386ee8.  With that fix, we can now run the importer locally, but the ETD collection record is still being clobbered per the "Steps to Reproduce".

I initially thought this might be due to a race condition caused by running imports in a separate thread, but looking at the code I don't think so anymore:
https://github.com/curationexperts/alexandria-v2/blob/master/bin/ingest-etd#L88-L95

Still, it might be worth testing what happens if we don't try to spawn a separate thread - I'm not sure what benefit that provides.
