### ISSUE TITLE
Display metadata on collection index partial.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#58]
Depends on #49

**Comment by val99erie** [comment]
![collection_index_page](https://cloud.githubusercontent.com/assets/298865/6189611/947c6cc8-b361-11e4-9dea-aa732560d218.png)

**Comment by val99erie** [comment]
According to the wireframe, it looks like they only want the (truncated) description on the index page, so I removed all the other fields.
