### ISSUE TITLE
CSS and CurationConcerns' .navbar

### ISSUE THREAD

**Issue by dunn** [curationexperts/alexandria-v2#592]
In dde8c412e437f1b3b1aca3e56238985548e4a65c Justin added CC's search-refine toolbar to the search view: https://github.com/curationexperts/alexandria-v2/blob/dde8c412e437f1b3b1aca3e56238985548e4a65c/app/views/layouts/alexandria.html.erb#L40-L46

Currently since it has the same class (`navbar`) as the top navigation bar, the styling is all muddled:
![screen shot 2016-02-18 at 2 51 04 pm](https://cloud.githubusercontent.com/assets/985416/13161661/07ecdd80-d654-11e5-9b1f-3a2e11c3ab08.png)

The obvious solution is to tweak our CSS, but should that CC view (https://github.com/projecthydra-labs/curation_concerns/blob/64eab4d87fac8b88367ebb5e34b4d34ad7ce6716/app/views/catalog/_navbar.html.erb) be a "navbar" at all?  Functionally it seems less focused on navigation than on refining an existing search.

**Comment by jcoyne** [comment]
I think we just need to override https://github.com/projecthydra-labs/curation_concerns/blob/64eab4d87fac8b88367ebb5e34b4d34ad7ce6716/app/views/catalog/index.html.erb and not render that navbar partial.

**Comment by dunn** [comment]
Oh, if we just don't want that partial at all, can these lines just be removed instead? https://github.com/curationexperts/alexandria-v2/blob/dde8c412e437f1b3b1aca3e56238985548e4a65c/app/views/layouts/alexandria.html.erb#L40-L46

**Comment by jcoyne** [comment]
@dunn no that's necessary for the show pages created by CurationConcerns  (presently the AudioRecording)
