### ISSUE TITLE
Admin user can't edit a record

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#60]
Issue:  When I log in as an admin user and visit the edit page for an Image record, I get an error instead of the edit form.
We suspect it might be an issue with authorization:
https://github.com/projecthydra/hydra-head/blob/f3da6a134e61b64e79d229d124de4e49cb686831/hydra-core/app/controllers/concerns/hydra/controller/controller_behavior.rb#L31

* [ ] An admin user can load the edit form
* [ ] Write a spec that would have caught this problem

**Comment by jcoyne** [comment]
I'm not having a problem with this.

**Comment by val99erie** [comment]
My mistake.  Before we had the edit link on the show page, I was trying to get to the edit page by typing in the URL directly, and I was using the wrong route.  Now that the link is there with the correct URL, there is no problem.  So, just chalk this one up to user error.

**Comment by jcoyne** [comment]
Phew!
