### ISSUE TITLE
Import Roles for Wax Cylinders

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#609]
See notes for field 100 (rows 12 & 13), field 110  (rows 14 & 15), field 700 (rows 51 & 52), and field 710 (rows 53 & 54) in the [cylinders-mapping-DRAFT](https://docs.google.com/spreadsheets/d/1pK76NWbComHoXPC_u_uVZ1DWrOtCG1JW17-WHJwaHac/edit#gid=0) spreadsheet.

If the field lacks a subfield $4 role specifier, have the importer log an error with enough data to locate the record.

For the sample data below, log an error something like this:

> WARNING: unable to determine role - SystemID: 002524079, field 700, "Seymour, Tot, 1889-1966"

```
<controlfield tag="001">002524079</controlfield>
. . .
<datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Jerome, M. K.</subfield>
    <subfield code="q">(Maurice K.),</subfield>
    <subfield code="d">1893-1977.</subfield>
</datafield>
<datafield tag="700" ind1="1" ind2=" ">
   <subfield code="a">Seymour, Tot,</subfield>
   <subfield code="d">1889-1966.</subfield>
</datafield>
<datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Farrell, Marguerite.</subfield>
    <subfield code="4">voc</subfield>
</datafield>
```

**Comment by val99erie** [comment]
From the spreadsheet:

----------------
field: 100
subfield:  $4 & $e

mapping notes: 
"Subfields 4 & e provide often provide more specific roles for creators/contributors.

If $e:
```
arranger of music = http://id.loc.gov/vocabulary/relators/arr 
author = http://id.loc.gov/vocabulary/relators/aut
composer = http://id.loc.gov/vocabulary/relators/cmp
conductor = http://id.loc.gov/vocabulary/relators/cnd
instrumentalist = http://id.loc.gov/vocabulary/relators/itr
librettist = http://id.loc.gov/vocabulary/relators/lbt
lyricist = http://id.loc.gov/vocabulary/relators/lyr
performer = http://id.loc.gov/vocabulary/relators/prf
singer = http://id.loc.gov/vocabulary/relators/sng
speaker = http://id.loc.gov/vocabulary/relators/spk
```

If $4:
```
arr = http://id.loc.gov/vocabulary/relators/arr
aut = http://id.loc.gov/vocabulary/relators/aut
cmp = http://id.loc.gov/vocabulary/relators/cmp
cnd = http://id.loc.gov/vocabulary/relators/cnd
itr = http://id.loc.gov/vocabulary/relators/itr
lbt = http://id.loc.gov/vocabulary/relators/lbt
lyr = http://id.loc.gov/vocabulary/relators/lyr
prf = http://id.loc.gov/vocabulary/relators/prf
sng = http://id.loc.gov/vocabulary/relators/sng
spk = http://id.loc.gov/vocabulary/relators/spk
voc = http://id.loc.gov/vocabulary/relators/sng
```

If blank (or not on list), then use performer = `http://id.loc.gov/vocabulary/relators/prf`

If multiple roles for one name, that name should ideally be imported twice (once for each role)."

----------------
field: 100
subfield:  $a $c $d $q
mapping notes: Concatenate selected subfields in order they appear in record. Map to "performer" role, unless more specific role is listed in $4 or $e.

**Comment by val99erie** [comment]
@mark-dce In your XML snippet above, could you please confirm that the datafield tag should be "100", not "700"?

**Comment by val99erie** [comment]
@mark-dce Could you provide sample data of the "$e" use case?

**Comment by val99erie** [comment]
@mark-dce Oh, I see, I'm missing some of the fields.  It looks like 700 is correct in your sample.  Could you provide sample data for the other cases?

**Comment by mark-dce** [comment]
@val99erie - the sample in the story was just meant to show an error case example.

There are a multiple occurrences of fields 100 and 700, and one example of field 710 in the sample data on the server at  `/data/metadata-cylinders/cylinders_samples_only_marc.xml`  

There's no example of field 700 in that sample set.  Can you extrapolate from the samples in fields 100, 700, and 710?  

Otherwise, save the results of the following pegasus query and there should be multiple examples of fields 100, 700 & 710, plus one example of 110:
http://pegasus.library.ucsb.edu:5661/sba01pub?version=1.1&operation=searchRetrieve&query=dc.format=wd&maximumRecords=500&startRecord=1

You can change the startRecord value to get different slices of the cylinder collection that may have different distributions of the sample fields (there are 10294 total MARC records in the cylinder collection).

**Comment by val99erie** [comment]
@mark-dce  ok thanks!

**Comment by val99erie** [comment]
@mark-dce Some questions:

1. Will any of these fields ever contain URIs, or are we assuming that they will always be a string?

2. Should the contributors be stored on the audio record as a string, or should we find/create local authorities?

3. If we use local authorities, how can I tell what type of local authority each contributor should be?  Should we just use Agent, the most generic type, or is there an indicator in the data file?

**Comment by val99erie** [comment]
TODO:
- [ ] Import field 100
- [ ] Import field 110
- [ ] Import field 700
- [ ] Import field 710
- [ ] Log message if subfield 4 doesn't exist

**Comment by mark-dce** [comment]
Answers to questions above - 
1. I don't think there's a provision to use URIs in the MARC standard.  For now assume that the source data will always be strings.  I'll confirm with Chrissy and update the ticket if I'm wrong.

2. We should follow the pattern we use for authors/creators on ETDs, which is to use a string for the contributor name.

3. We won't need to know the type if we store the data as strings rather than local authorities, so that's another reason to just store strings.

**Comment by val99erie** [comment]
After this morning's discussion with UCSB team, it sounds like there is a fairly simple mapping for how to tell which type of local authority it should be.  Chrissy will update the metadata mapping spreadsheet with that info.  cc @chrissyrissmeyer

**Comment by chrissyrissmeyer** [comment]
MARC21 uses a consistent naming pattern for the field names.

X00  (ind1="1 or 2") = personal name
X00 (ind1="3") = family name
X10 = corporate/organization name
X11 = conference/meeting name

Likewise,
1XX = main entry (e.g., the primary creator)
6XX = subject
7XX = additional entry (e.g., additional creators/contributors)

The two patterns can be combined (e.g., X10 + 7XX = corporate name as an additional creator, 6XX + X10 = corporate name as a subject). For additional details see: https://www.loc.gov/marc/bibliographic/bdheading.html

I updated in the Google doc with this information as well.

**Comment by val99erie** [comment]
100 (ind1="0" or "1") is a personal name
100 (ind1="3") is a family group name

110 is a organization name

700 (ind1="0" or "1") is a personal name
700 (ind1="3") is a family group name

710 are organization names

**Comment by val99erie** [comment]
@mark-dce The story says that a warning should be printed if subfield 4 doesn't exist, but it looks like subfield e is sometimes used to determine a contributor's role.  I'm going to code it to print a warning if both 4 and e are missing.  Please let me know if that's not what you intended.

**Comment by mark-dce** [comment]
@val99erie - That sounds great, I really just meant log a warning if the role can't be determined.
