### ISSUE TITLE
Catalog search should search title or subject when "All Fields" is selected

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#61]
The search doesn't seem to be hooked up.  If you type something in the search bar, you get 0 results.

**Comment by val99erie** [comment]
Question:
* [ ] For the regular catalog search (not advanced search), which fields do we need to search on?

**Comment by val99erie** [comment]
I wired up the search for "title" and "subject", but the "all fields" search isn't working yet.
* [ ] Fix "All Fields" search

**Comment by acozine** [comment]
Let's stick with Title, Subject, and All Fields. The dropdown currently includes Author, which we should either hide or rename the label and hook it up to search the Creator field.
