### ISSUE TITLE
Update cylinder importer to use cylinder collection record

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#610]

**Comment by ilessing** [comment]
@chrissyrissmeyer can probably best answer this question.  I guess she will have to create a collection level record for Cylinders

**Comment by chrissyrissmeyer** [comment]
Yes, I will need to create a collection record for cylinders. I will add that to my to-do list for today.

**Comment by chrissyrissmeyer** [comment]
@jcoyne I have added a cylinders collection record to the adrl-dm/ingest-ready folder in Stash.The csv file should incorporate the recent metadata related changes, but please let me know if I missed anything.

**Comment by jcoyne** [comment]
@chrissyrissmeyer I'm only seeing an .xlsx file here: https://stash.library.ucsb.edu/projects/CMS/repos/adrl-dm/browse/ingest-ready/cylinders/cylinders-collection.xlsx Should that be converted to csv?

**Comment by jcoyne** [comment]
Fixed by ab3f735
