### ISSUE TITLE
Configure such that the minter state file goes to a persistent (and backed up) directory.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#614]
Check that the minter_state file is set to a good location for production:
https://github.com/curationexperts/alexandria-v2/blob/master/config/application.yml.template#L7

**Comment by acozine** [comment]
The location of the minter-state file can be set via Ansible in the alexandria role - the default location is in the shared/ directory: https://github.com/curationexperts/alexandria-v2/blob/master/ansible/roles/alexandria-v2/defaults/main.yml#L8
