### ISSUE TITLE
Implement a date slider

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#63]
Since UCSB's objects have ranges as well as direct dates, the facet for Date should be implemented as a slider.

**Comment by mark-dce** [comment]
See if this can be used https://github.com/projectblacklight/blacklight_range_limit

**Comment by acozine** [comment]
Depends on #44

**Comment by mark-dce** [comment]
Requires upgrade to Blacklight 6.  Working on dependencies.
