### ISSUE TITLE
Bookmarks looks wrong in grid view

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#642]
<img width="905" alt="screen shot 2016-03-02 at 7 01 53 pm" src="https://cloud.githubusercontent.com/assets/92044/13481199/482f4568-e0a9-11e5-9243-48d58401b9e3.png">

**Comment by jcoyne** [comment]
@dunn I think this ticket and #623 is related to the change you made to the bookmarks style.

**Comment by dunn** [comment]
Yeah, probably. Unfortunately the only image collection with up-to-date metadata is the Carl Rogers collection and ingesting it with the latest code is leading to broken image URLs:
![screen shot 2016-03-03 at 10 32 31 am](https://cloud.githubusercontent.com/assets/985416/13504921/82f7cb66-e12b-11e5-98c3-41849a890470.png)
The URLs it's trying to fetch look like
```
http://localhost/images/8p58pc92q%2Ffiles%2Faaa671ff-3621-4a72-9bb3-cb06676816f4/full/300,/0/default.jpg
```
So I'll start looking into this but I might not be able to propose a real fix until I can get a proper local collection set up.
