### ISSUE TITLE
Image importer:  Alternative title

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#65]
The mods parser is currently not specific enough when it imports the title.

This field in the MODS file:
mods:titleInfo@usage(primary)/title

* [ ] Should map to DC:title

But this:
mods:titleInfo@type(abbreviated, translated, alternative, uniform)/title

* [ ] should NOT map to DC:title

according to lines 9 & 36 in the spreadsheet:
https://docs.google.com/a/gentiansoftware.com/spreadsheets/d/1YnWQOKsbwfbToGYt018Q3CRXLycysUJ2S6o3j8SpvzI/edit#gid=513417340

Note:  This story is just about the primary title.  The (abbreviated, translated, alternative, uniform) title will be handled in a different story.

**Comment by jcoyne** [comment]
How about mapping it to `DC.alternative`?

**Comment by jcoyne** [comment]
No abbreviated, translated, or uniform titles appear in the sample data

**Comment by mark-dce** [comment]
DC.alternative is good for alternativeTitle 
We'll ask for sample data.

**Comment by jcoyne** [comment]
Other titles are now on #66. This ticket is now just about "alternative title"
