### ISSUE TITLE
Do we need to support abbreviated, translated, or uniform titles?

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#66]
They are not in the sample data.

**Comment by mark-dce** [comment]
Chrissy is researching whether UCSB needs these forms of alternate titles.  We'll leave this ticket open in the current sprint (and move it forward) until we have an answer.

**Comment by val99erie** [comment]
This seems to have been answered already, since I just finished working on the same story #121.  I'll close this story as a duplicate.

**Comment by mark-dce** [comment]
Yup - my bad - they were duplicates
