### ISSUE TITLE
ETDs and Images should use solr_document_url in Content Negotiation.

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#660]
Instead of using polymorphic_url
https://github.com/curationexperts/alexandria-v2/blob/master/config/initializers/hydra_config.rb#L30

You should be able to get the ttl (e.g. http://ucsb.curationexperts.com/lib/ark:/48907/f3zw1j3s.ttl) from an ETD or Image

**Comment by val99erie** [comment]
Duplicate story #665.
