### ISSUE TITLE
size the form field for Title

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#67]
On the edit page, the form field for Title should be the same width as the other fields on the page. Right now it can get wider as you widen the browser.

![screen shot 2015-02-17 at 11 16 12 am](https://cloud.githubusercontent.com/assets/879121/6233122/7a5e5364-b696-11e4-9974-bc5372da40fe.png)

**Comment by jcoyne** [comment]
see `.multi_value .listing, .controlled_vocabulary .listing` for the max-width on the others.

**Comment by tonyc** [comment]
Fixed in 0ab71abf301ab9fb76cf7f513a84879fc5da2925
