### ISSUE TITLE
MODS importer:  language

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria-v2#71]
Add the "language" field to the mods parser.

* [ ] Imports language(s) for an Image
* [ ] Imports language(s) for a Collection

Field in MODS file:
mods:language/languageTerm@valueURI

**Comment by val99erie** [comment]
Question:  Will there always be a valueURI attribute?  What should we do if it is missing?  Just import the text?

**Comment by jcoyne** [comment]
Raise an error if valueURI is missing.
