### ISSUE TITLE
On the show page, allow users to download the object's metadata from Fedora

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#76]
As an admin, I want to look at all the metadata on an object, especially those fields that are not editable in the GUI. This could be a feature to trumpet to the world - UCSB provides open linked data for its digital collections! Add a link to download all the metadata from Fedora in TTL format on the object Show page. 

If UCSB wants to restrict this functionality to Admins, we'll need to move the link to the object Edit page and restrict access to the download so users can't use the URL pattern to bypass the intended restriction.

**Comment by jcoyne** [comment]
```ruby
Image.new.resource.dump(:ttl)
```
