### ISSUE TITLE
Import language

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria-v2#79]
Expressed in MODS as:
mods:language/languageTerm@authority(iso639-2b)@type(code)
Sample from image :
```xml
		<mods:language>
			<mods:languageTerm authority="iso639-2b" type="code" authorityURI="http://id.loc.gov/vocabulary/iso639-2" valueURI="http://id.loc.gov/vocabulary/iso639-2/eng">eng</mods:languageTerm>
		</mods:language>
```
Sample from collection record - the photograph collection is marked "no linguistic content / not applicable" :
```xml
	<mods:language>
		<mods:languageTerm authority="iso639-2b" type="code"
			authorityURI="http://id.loc.gov/vocabulary/iso639-2"
			valueURI="http://id.loc.gov/vocabulary/iso639-2/zxx">zxx</mods:languageTerm>
	</mods:language>
``` 
Property name: language
Predicate: RDF::DC.language

Note: This is for line 24 of the spreadsheet - primary language of the object rather than language of cataloging.

**Comment by jcoyne** [comment]
Is this same as #71?

**Comment by acozine** [comment]
Yes. Closing in favor of #71.
