### ISSUE TITLE
mods:url path suffix

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#81]
UCSB has indicated a need for a path like
http://alexandria.ucsb.edu/lib/ark:/48907/f3bg2kw5/mods:url
for OAI harvesting.

In Alexandria-1, this seems to resolve to the same view as the same URL without the /mods:url suffix.

Ask UCSB 
* Whether this indicates an implicit requirement for a view displaying the object metadata serialized to mods?
    * if YES, can we use the rails convention of .mods (or just .xml) to specify format and whether the harvesters could use straight RDF (.rdf) instead (cheaper, easier, more fashion forward)
    * If NO, can we drop the /mods:url suffix entirely or do specific harvesters require this?

Create additional tickets as appropriate based on answers to question.

**Comment by jcoyne** [comment]
Do we need full OAI-PMH support? I suspect this would be a rather large chunk of work. ResourceSync would probably be slightly easier.

**Comment by jcoyne** [comment]
http://www.openarchives.org/OAI/openarchivesprotocol.html

**Comment by mark-dce** [comment]
California Digital Library (CDL) harvesting for Calisphere is going to rely a subset of OAI-PMH.  There's a chance UCSB could get them to pilot resource sync with turtle metadata exchange, but it's probably low.

See the guidelines here: http://www.cdlib.org/services/access_publishing/dsc/contribute/docs/GDO.pdf - particularly section 3 (METS Guidelines) and Appendix A (Descriptive Metadata Guidelines)

**Comment by ilessing** [comment]
CDL and UCSD are contemplating using Resource Sync for harvesting.
We can close this with a "Won't Fix"
