### ISSUE TITLE
Rename default path from 'catalog' to 'lib'

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#89]
The path for the catalog controller should be renamed

- [x] The default route for an item should be /lib/:id
- [X] ~~The path for search results should be /lib?page...~~
- [x] The homepage should be at / and is not the same as the default catalog controller route /lib

For details on the default catalog controller path see #90

**Comment by jcoyne** [comment]
I'd rather not take on the second bullet point. I don't think it's required.

**Comment by mark-dce** [comment]
Found alternate solution for second requirement - otherwise look's good
