### ISSUE TITLE
Append transformation text to recordOrigin

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#99]
Append the following text to each record_origin string.  Save this text if no recordOrigin node exists in the source MODS file:
"Converted from  MODS 3.4 to local RDF profile by ADRL."

- [x] this suffix is added on import

**Additional Context**
For new objects created directly by ADRL (not imported) use the text
"Record originated in ADRL."

If you want to get fancy, add a configurable version number to ADRL (but don't hardcode it in both places).

**Comment by val99erie** [comment]
@mark-dce  a couple questions:

* Should the text always be appended?  Or only when there is no other text?

* If you run the importer 2 or 3 times in a row, should it keep appending the text, or only add it once?

**Comment by mark-dce** [comment]
For import purposes the MODS parser should always append "Converted from MODS 3.4 to local RDF profile by ADRL."

The other was just to say have the parser add this, for items originally created in ADRL 2.0, it wouldn't make sense to have the conversion message.

**Comment by val99erie** [comment]
@mark-dce   Okay, sounds good.  Can you clarify:  If I run the importer 3 times for the same object, should the record_origin contain that message 1 time or 3 times?

**Comment by mark-dce** [comment]
hmm - I guess I don't know what the current importer behavior is for other items - If you ran it three times, would you get three copies of the title or just one?  If you get three copies of the title, then you should get three copies of the string for parallelism; if you only get one copy of the Title, I would expect to get one coy of what's in record_origin with the suffix string appended just once.

**Comment by val99erie** [comment]
Ah, you're right.  I was making it into a harder problem than it needed to be.

**Comment by mark-dce** [comment]
In the future we might need to consider concatenating the two strings into a single object:

<http://www.loc.gov/mods/rdf/v1#recordOrigin> "Converted from CSV to MODS 3.4 using local mapping.  Converted from MODS 3.4 to local RDF profile by ADRL";

Instead of two objects for the same predicate (current):

<http://www.loc.gov/mods/rdf/v1#recordOrigin> "Converted from CSV to MODS 3.4 using local mapping.",
     "Converted from MODS 3.4 to local RDF profile by ADRL";

For now, though, I think it would also be sufficient to add a timestamp to the string the ADRL parser creates.

**Comment by val99erie** [comment]
After discussion with Mark and Justin:  prefer timestamp

**Comment by tonyc** [comment]
:hammer:
